### ISSUE TITLE
Doorbell not in Home App

### ISSUE THREAD

**Issue by Bladestar2105** [ebaauw/homebridge-nb#1]
Hello,

your Plugin just works fine. I have the opener and a smart lock.
In somebody rings the Doorbell I get a notification from the Home App. But I dont see the Doorbell in the Home App.
Thanks for your help 🙂

**Comment by ebaauw** [comment]
That’s one of Apple’s quirks.  It is visible in Eve, but you cannot set an action from the accessory view.  However, if you create a new automation in Eve, you can select the doorbell as trigger.  Note that it only sends _Single Press_.

**Comment by Bladestar2105** [comment]
Okay thank you.
It would be nice to use it in the Home app too. Maybe in the future?... :-)

**Comment by ebaauw** [comment]
You’ll have to ask Apple.

**Comment by Bladestar2105** [comment]
But in the home app under "properties of home" there is "cameras & ring bells". It would be nice to see the opener there 👍

**Comment by ebaauw** [comment]
Yes it would.  Can you tell me how to get it there?  Or do you know of another plugin that does?  As far as I can tell Home only plays nice with video doorbells.

**Comment by Bladestar2105** [comment]
Unfortunately I don't know of any other plugin 😞 
I have two eufy Homekit cameras with motion sensor, they are shown there.

**Comment by ebaauw** [comment]
I double-checked: exposing the _DoorBell_ service in a separate accessory leads to another _Not Supported_ tile, but still no entry in the notification settings.

**Comment by sewshoetz** [comment]
Hello ebaauw, 

i´ve installed your plugin homebridge-nb, first of all, thanks for your great work!

May i ask you something, concerning the opener-bell-service:
I wanted to trigger a automation, when someone rings the bell.
The plug in shows up in the devices section (screenshot attached), but when i ring the bell, the switches don´t change in any form. 
What i´m wrong about, could you give me some advice, how to make it happen, that the switch reacts when someone rings the bell outside, which is connected to the opener?

Would be nice, perhaps it´s an rookie-error, me as newbie could take the blame on me ... :)

Thanks in advance,
Greets from Vienna, 
Johannes 
<img width="534" alt="Bildschirmfoto 2022-03-19 um 12 29 46" src="https://user-images.githubusercontent.com/101731048/159119458-dc1dacab-5e82-4b1c-82a8-7f12fdecaa30.png">
