### ISSUE TITLE
Plugin port change upon restart

### ISSUE THREAD

**Issue by Jabka71** [ebaauw/homebridge-nb#10]
Hi,

Looks like the plugin port changes each time Homebridge restarts. The Nuki Bridge only supports 3 registered callback adresses, so each time the plugin changes its port a new callback registration is made. Once at 3 registrations the plugin fails to register with the following error messages:

subscribe to event notifications
error: too many callbacks registered

Any way to use a fixed port for the plugin which would remain the same upon restarts ?

Thanks.

**Comment by ebaauw** [comment]
No, because it's not needed.

How do you stop homebridge?  Homebridge NB removes the callback when shut down gracefully.  See #9.
