### ISSUE TITLE
Doorbellservice on individual HomePods

### ISSUE THREAD

**Issue by beatpaul** [ebaauw/homebridge-nb#102]
Hi Erik!
I used this plugin for quite some time and it works great. Thanx again for your work!
These days I bought a second HomePod for my daughter and my question is if it is possible to turn on/off the doorbell service from nuki Opener for individual HomePods since I don't want the HomePod of my daughter ringing at night.
I couldn't find any settings related to this in the home app or Eve App.

thx, Paul

**Comment by ebaauw** [comment]
Not that I know, see also #79.

**Comment by beatpaul** [comment]
Ok :(
Thanks for your quick answer!
