### ISSUE TITLE
Prevent unlatch when lock is locked

### ISSUE THREAD

**Issue by cerahmed** [ebaauw/homebridge-nb#106]
Hi there, great great zero-conf plugin! Really love it.

I've been using [hombridge-nuki](https://github.com/lukasroegner/homebridge-nuki#readme) until I changed to homebridge-nb today.

One feature I'm really missing from homebridge-nuki plugin is the option to _prevent unlatch when lock is locked_. Meaning, _unlatch only works when the lock is unlocked_ for extra safety.

Anyway to memic that behavior with this plugin?

**Comment by ebaauw** [comment]
I'm not going to do that.  I would be another setting in config.json, kinda negating the whole zero-config philosophy.

**Comment by cerahmed** [comment]
Agree with the last part, however I thought maybe that should be the default as it is more logical to prevent a latch operation when the lock is locked.

This issue will be closed as such.

**Comment by ebaauw** [comment]
You can prevent the latch form being exposed as separate accessory.  You could probably create an automation in _Shortcuts_ or some home automation platform, that sets _Latch_ on the lock accessory only when the lock is unlocked.

**Comment by cerahmed** [comment]
I already disabled the latch from the settings of the plugin.
Any idea how I'd go about doing such an automation? It sounds really usefull if I could attach the latch to the lock accessory only when it's unlocked.

**Comment by ebaauw** [comment]
HomeKit doesn't like configuration changes, so optionally exposing an accessory, service, or characteristic won't work.  Just create a dummy switch, and an automation to set the _Latch_ characteristic when that switch is activated, and the lock is unlocked.  Use a decent HomeKit app, like Eve to see the _Latch_ characteristic, as Apple's Home doesn't support custom characteristics.
