### ISSUE TITLE
How to exclude a Nuki in the conf?

### ISSUE THREAD

**Issue by francescosabia** [ebaauw/homebridge-nb#107]
Hello! I don t know if it s possible and if yes how to do.. but I have 2 Nuki and only one I need to use with the plugin.. how to exclude the other one? Thanks

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-nb/issues/69#issuecomment-1545583873

**Comment by francescosabia** [comment]
Can t find the voice “setting” in the UIInviato da iPhoneIl giorno 23 mag 2023, alle ore 07:27, Erik Baauw ***@***.***> ha scritto:﻿
See #69 (comment)

**Comment by francescosabia** [comment]
Can u send me a sample of the config with a white list so I can adapt to my Nuki id? ThanksInviato da iPhoneIl giorno 23 mag 2023, alle ore 08:56, francesco sabia ***@***.***> ha scritto:﻿Can t find the voice “setting” in the UIInviato da iPhoneIl giorno 23 mag 2023, alle ore 07:27, Erik Baauw ***@***.***> ha scritto:﻿
See #69 (comment)

**Comment by ebaauw** [comment]
I cannot, as I don’t have any.  I suggest you use the plugin _Settings_ dialogue in Homebridge UI, if you’re intimidated by json.

**Comment by ebaauw** [comment]
Best ask HOOBS support.  I don’t know HOOBS and recommend using a standard Homebridge installation.
