### ISSUE TITLE
Add option to manually set API token

### ISSUE THREAD

**Issue by timgrewe** [ebaauw/homebridge-nb#111]
Could you maybe add an option to manually set the API token for the bridge? My bridge is currently reporting the wrong token in response to the `/auth` call (the response token is the actual token followed by the Wi-Fi SSID, see [here](https://developer.nuki.io/t/bridge-api-auth-includes-ssid-in-token-response/21733)).

Because of this, I currently cannot use the plugin since it always obtains the incorrect token.

**Comment by ebaauw** [comment]
> My bridge is currently reporting the wrong token in response to the /auth call (the response token is the actual token followed by the Wi-Fi SSID, see [here](https://developer.nuki.io/t/bridge-api-auth-includes-ssid-in-token-response/21733)).

That's a first.  Did you try and disable and re-enable the HTTP interface?  And reset the bridge?  Are the system clocks on the bridge and the server running Homebridge synchronised?

What's the output of:  
`nb -DD -H `_ip-address_` auth`

And of:  
`nb -DD -H `_ip-address_` -T `_token_` info`
