### ISSUE TITLE
NB CLI Command Fail

### ISSUE THREAD

**Issue by cerahmed** [ebaauw/homebridge-nb#112]
Hi there,

I'm trying to use the cli utility to get some information about the connected Nuki Bridge.
Assuming that I don't know anything about the Nuki bridge (IP, port, etc..), I tried to first run `nb info`, which failed with the following error: `nb: fatal: Missing host.  Set NB_HOST or specify -H.`

So I assumed I might have to supply the command with some more information, so I ran `nb info -h` to get the command's required information, however I still get the same error when adding the help flag: `nb: fatal: Missing host.  Set NB_HOST or specify -H.`

Am I missing something?

**Comment by ebaauw** [comment]
Run `nb -h` to see the generic options for `nb`, like `-H`.  Use `nb discover` to find the Nuki bridge.

**Comment by cerahmed** [comment]
Indeed, `nb discover` works. However what I'm after is get information about the Bridge (token to be specific).
I tried `nb info` with and without the host ip and it gives the same error.
Then tried `nb info -h` for useful information on how to use the command and it gave the same error mentioned above.

Appreciate your help.

**Comment by cerahmed** [comment]
Ok nevermind. After some trials it seems that I have to do the following:

1) Run `nb discover` to get the bridge IP Address.
2) Run `nb -H <IP_ADDRESS> auth` to get the token.
3) Perform `nb -H <IP_ADDRESS> -T <Token> info` to get bridge info.
