### ISSUE TITLE
Callback remove

### ISSUE THREAD

**Issue by Twisi** [ebaauw/homebridge-nb#113]
Hi, I have a problem with deleting the callback. When I enter the command "nb -H X.X.X.X:8080 -T (token) callbackList" 3 callbacks are displayed. When I enter the command "nb callbackRemove" it shows "nb: fatal: Missing host. Set NB_HOST or specify -H.". So how do I clear the callback? Thank you

**Comment by Twisi** [comment]
Yes, I did: nb -H 10.0.0.8:8080 -T 037267 callbackRemove. 
Then ID missing: nb callbackRemove: fatal: parameter id missing usage: nb callbackRemove [-h] id. 
I add -h and ID and this is there: Remove Nuki bridge subscription.

Usage: callbackRemove [-h] id

Parameters:
  -h, --help
  Print this help and exit.

  id
  Remove callback with ID id (from nb callbackList).

See https://github.com/ebaauw/homebridge-nb for more info.

Thank you very much

**Comment by ebaauw** [comment]
You need to tell it which callback you want to remove.

**Comment by Twisi** [comment]
I have it. I used -h before the ID. That was the mistake. Thank you
