### ISSUE TITLE
Spam Homebridge log less

### ISSUE THREAD

**Issue by maxb911** [ebaauw/homebridge-nb#12]
Thanks for plugin! It’s been working reliably for a me for a couple of days! So I use it instead of the native Nuki HomeKit integration now.

I just have one issue with it. It does write an entry into my homebase log every single minute, which makes the log pretty much unreadable. Could you please integrate a flag that allows for less detailed logging? Thanks!

**Comment by ebaauw** [comment]
You can change the log level at runtime through the _Log Level_ characteristic.  Use Eve or another decent HomeKit app for this, as Home doesn't support custom characteristics.  See also https://github.com/ebaauw/homebridge-lib/issues/26.

**Comment by maxb911** [comment]
Sorry, I didn't see the other closed issue. Changing the characteristics via the Eve app seems to have worked. Thanks!
