### ISSUE TITLE
V 1.4.5 Don't expose Battery Level nor Charging State on Battery service for Opener.

### ISSUE THREAD

**Issue by hassounet** [ebaauw/homebridge-nb#121]
Why remove this feature ? I’m now revering back to 1.4.4 to get battery % again

**Comment by ebaauw** [comment]
Because the Opener doesn't report these.  I though they were mandatory on the _Battery_ service in HomeKit, but they aren't.  The percentage reported in earlier version is fake, derived from the battery critical status reported by the Opener.
