### ISSUE TITLE
Homebridge version 1.6.1 dependency error

### ISSUE THREAD

**Issue by cereyanli** [ebaauw/homebridge-nb#122]
I am running Homebridge 1.6.1 on a docker hosted by Synology NAS and homebridge-nb v1.4.8 installed and configured and properly working but HB log shows this error message 

The plugin "homebridge-nb" requires a Homebridge version of ^1.6.1 which does not satisfy the current Homebridge version of 1.6.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Comment by ebaauw** [comment]
Check for multiple Homebridge installations.

I list the version I use for development and testing; other versions might work… or not.  I simply don’t have the bandwidth to test them.

**Comment by cereyanli** [comment]
@ebaauw thanks for the response 

But why does this error message come even though my HB version (1.6.1) meets your plugin requirements

**Comment by ebaauw** [comment]
You probably have Homebridge installed in multiple locations.  The message is from Homebridge itself, and it clearly thinks it's version 1.6.0.  What Homebridge version does Homebridge NB report on startup (right after the "Initializing NB platform..." message from Homebridge).  And what version does Homebridge report right after the QR code?
