### ISSUE TITLE
Unnecessary logs regarding the last update

### ISSUE THREAD

**Issue by maxileith** [ebaauw/homebridge-nb#123]
Hello,

I would like to point out an issue that I have with this plugin. It is nothing functional but it bothers me when looking at the logs. The plugin logs the last update time every minute. This basically floods the logs, especially noticeable when you are not at home since no other plugin logs when nothing is happening. I think the plugin should only log on state changes or when an update attempt fails. Logging the last update timestamp should rather be on debug loglevel.

Looking forward to your thoughts on that @ebaauw .

**Comment by ebaauw** [comment]
Set _Log Level_ on the accessory to 0 suppress the log messages.

**Comment by Maxiklaxi** [comment]
I feel the same as Maxi does. It's an unnecessary amount of logs. I want to see changes and important things in my logs. I also want to see when the status of my door changes and not disable all logs about it.
I would really look forward to see a small update update there.

**Comment by ebaauw** [comment]
>  I want

You're more than welcome to write your own plugin.

**Comment by Maxiklaxi** [comment]
I am not a developer, so im not able to do that.
But anyways, i am right now having the following issues:

Im trying to find a bug with another homebridge plugin which appears approx every 2.5 hours, but the logs are getting spammed away from nuki. So i thought to myself "Im getting all Nuki logs in my Nuki App on my Phone if i really need them" so ive tried your command:

> Set _Log Level_ on the accessory to 0 suppress the log messages.

`        {
            "name": "Nuki",
            "latch": true,
            "port": 9999,
            "platform": "NB",
            "_bridge": {
                "logLevel": 0,
                "username": "0E:3F:A8:BB:72:3F",
                "port": 46423
            }
        },` 

(i also tried the command outside the bridge settings (below name), but that didnt work either)
Im still getting all the logs. Where do i need to put the command?

Im also experiencing a bug where sometimes the door latches, even if im not using the latch button, with the unlock button which should not latch it. I can try to reproduce that for you and send you the logs.
