### ISSUE TITLE
Possibility to remove doorbell

### ISSUE THREAD

**Issue by YTKengo** [ebaauw/homebridge-nb#125]
Hello,

could you please add an option to remove the doorbell from the opener or at least add the doorbell as device. The second option would be more comfortable because then you can decide wich homepod should play a doorbell sound and which not.

Thanks for your work!

Best wishes

**Comment by ebaauw** [comment]
No, won’t do.  You can already set _Enabled_ on the _Doorbell_ service to off, so it won’t trigger.  See #79.
