### ISSUE TITLE
Nuki Smart Lock 4

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-nb#126]
Upgraded my old Smart Lock 2 to a new Smart Lock 4.  The Nuki Bridge seems to expose it just like a Smart Lock 3, except for the firmware version.  Still waiting on the door sensor (didn't realise that's now external), but I don't expect any differences from the Smart Lock 3 either.

I managed to link it to HomeKit over Matter, following the instructions from the Nuki app.  HomeKit shows it as an accessory with a single _Lock Mechanism_ service.  No support for the open door (unlatch) function yet (should become available with the 2024 firmware upgrade).  It shows up in Eve under _Thread Network_ as an endpoint, but Eve doesn't seem to get any additional information from probing it.

Note that the _Manufacturer Name_ is exposed a `"Nuki"`, not `"Nuki Home Solutions GmbH"` as Homebridge NB does.  I'll change that, so Home will show the link to the Nuki app (under the accessory settings).
UPDATE: Apparently, Home now only shows the app for certified and Matter accessories.

**Comment by ebaauw** [comment]
I think Apple has delayed support for Matter 1.2 to iOS 18.1.

**Comment by piejanssens** [comment]
https://www.reddit.com/r/HomeKit/comments/1hfrjps/its_finally_here/#lightbox
