### ISSUE TITLE
Plugin does not work with Nuke Smart Lock Pro (4th Generation)

### ISSUE THREAD

**Issue by rakez321** [ebaauw/homebridge-nb#127]
Hi,
apparently I can't use the plugin with the Smart Lock Pro (4th Generation) which has the WLAN Module integrated. Will there be an update in the future where the plugin is usable without the WLAN Bridge or is there a workaround right now?

**Comment by ebaauw** [comment]
> I can't use the plugin with the Smart Lock Pro (4th Generation)

Yes you can, using a Nuki bridge.  See the README: “This Homebridge plugin exposes Nuki Smart Lock and Nuki Opener devices, **connected to a Nuki Bridge**, to Apple's HomeKit.”

> Will there be an update in the future where the plugin is usable without the WLAN Bridge

You’ll have to ask Nuki.  They haven’t implemented the HTTP API on the smart lock pro 3 nor pro 4.  In fact, they haven’t even published any other local API to access the smart lock 3 pro nor 4 pro directly over WiFi.  See https://developer.nuki.io/page/documents/1/.  

> is there a workaround right now?

Best use the native HomeKit function of the smart lock.  I don’t know if this actually uses WiFi (I don’t have any smart lock pro).  I did pair my smart lock 4 (not pro) to HomeKit over Matter over Thread, and that seems very responsive.  Of course, you need an Apple Thread border router for that.  And unlatch doesn’t work yet, as it needs a Matter update.

**Comment by rakez321** [comment]
Thank you very much for the fast respond :) I guess I will have to wait for the matter update then ;)

**Comment by ebaauw** [comment]
Matter already works today, for lock and unlock.  The next version of Matter is needed only for the unlatch (open) function.  See also #126.
