### ISSUE TITLE
Change heartrate 

### ISSUE THREAD

**Issue by bytman** [ebaauw/homebridge-nb#128]
Hey, I got my opener today and it works fine with your plugin. Thank you for your work. 

One thing is I don’t understand, when anybody rings and the doorbell is enabled, my HomePod gives a sound long after my normal doorbell rings. 

The notifications from home and nuki comes immediately at the same Time. 

Would it help to set the heartrate of the bridge to 10s in the eve app? 

Thank you

Marco

**Comment by ebaauw** [comment]
No, it wouldn’t.  If you see the notification in Home immediately, Homebridge NB sends it to HomeKit immediately.  The Nuki bridge sends push notifications to Homebridge NB (through its callback mechanism); the polling is mostly a fallback for that.

I have no idea why the HomePod takes this long to respond (mine does at well).  As far as I can tell, it is caused somewhere in Apple’s domain.

**Comment by bytman** [comment]
Thank you for your very quick response. 

Maybe it will fix itself, by an software update from apple. 

An other question is, can I change the HomePod which will ring, at the moment the HomePod in the bathroom rings, it would be great when it rings in the living room or I can choose several HomePods.

**Comment by ebaauw** [comment]
No, see https://github.com/ebaauw/homebridge-nb/issues/79.
