### ISSUE TITLE
The Classic "Too Many Callbacks"

### ISSUE THREAD

**Issue by kloibs** [ebaauw/homebridge-nb#130]
Hi all, I've seen multiple issues regarding the too many callbacks prompt and have tried all of the various results mentioned in the respective issues. 

**This is what I try in terminal**
nb -H [IP address] -T [API token] callbackRemove

**And get this in response:**
nb callbackRemove: fatal: parameter id missing
usage: nb callbackRemove [-h] id

I appreciate any and all help!

**Comment by ebaauw** [comment]
As the error indicates, you need to specify the id of the callback to remove.
