### ISSUE TITLE
Never unlatch using Nuki, use opener or other device instead

### ISSUE THREAD

**Issue by nixmeer** [ebaauw/homebridge-nb#131]
Hi :)
As with almost all detached homes in Germany, we have a front door and an intercom that can operate a door buzzer. If I use the Smart Lock to unlock and unlatch the door, it opens a little and stays in this position after the latch is released. If I open but no one goes through the door and closes it afterwards, the door stays open. However, this doesn't happen if the door buzzer is being used instead of the latch. Nevertheless, using the door buzzer immediately doesn't make sense; I'd rather have it "wait" for the Smart Lockto unlock the door.

So here's what I'd like:

- "Locking the door" lock the door using the Smart Lock
- "Unlock the door" unlocks the door using the Smart Lock
- "Open the door"
  - if locked, instructs the Smart Lockto unlock the door and waits for the Smart Lockto complete, then triggers the Opener
  - if unlocked, instantly trigger the Opener
  
And here's the premium: It would be cool, if I didn't need to buy a bridge and an opener for that but could use any switch/button in my home as the opener (maybe though some kind of automation).

It might be that there already is a way to implement what I want though automations. Please share your ideas!

**Comment by ebaauw** [comment]
I'm afraid,  don't have much experience with buzzers.  The doorbell/intercom/buzzer installation in my apartment works fine with the Nuki Opener, and I've been using that.

> if locked, instructs the Smart Lockto unlock the door and waits for the Smart Lockto complete, then triggers the Opener
if unlocked, instantly trigger the Opener
> It might be that there already is a way to implement what I want though automations.

I suppose this could be automated, but might be a bit tricky.  I think it requires three automations and a flag (or dummy switch).  On "open the door", when the door is locked, you'd set the flag and unlock the door.  On the door reporting it's opened, when the flag is set, you'd activate the buzzer and clear the flag.  On "open the door", when the door is unlocked, simply activate the buzzer.

> It would be cool, if I didn't need to buy a bridge and an opener for that but could use any switch/button in my home as the opener

I suppose, if you can figure out which wires activate the buzzer, you could short them using a relay.  This could be a Zigbee smart relay, with Homebridge deCONZ, or a relay controlled through a Raspberry Pi GPIO pin, with Homebridge RPi.  I suppose there's many other types of relays, integrated in HomeKit, but I have no experience with these either.

You might also consider a low-tech solution: install a mechanical door closer to keep the door closed, even when unlatched.  It seems a bit superfluous to use both a lock and a buzzer, although, I suppose, you would this for what we would call a "night lock".

**Comment by nixmeer** [comment]
Hi Erik,

I build my entire smart home using hb, esp8266s and mqtt. I am able to install something else than the opener. And I am able to install a mechanical door closer, but that is not the point I am trying to make. The point is: this setup is the absolut standard in detached homes in the DACH area.

The question is: is there anyone willing to implement something like a "detached home front door" (dhfd) mode that has a "use opener" bool parameter? 
a) with "use opener" set to `true`, the dhfd mode creates three buttons (see post above) or a lock and a button (lock for locked and unlocked, button for buzzer). The lock (or two of the buttons) lock and unlock the smart lock. The additional button checks if the smart lock is unlocks, and if so tells the opener to open or tells the smart lock to unlock, waits for the smart lock to be done and afterwards tells the opener to open.
b) with "use opener" set to `false`, the dhfd mode creates the same three buttons (or lock and one button) as in a) and an additional sensor (door contact?). Everything stays the same except for the opener. Instead of triggering the opener, the sensor state is changed. One can then attach any HomeKit/Homebridge device to this sensor using an automation; no need to buy bridge and opener then.

**Comment by ebaauw** [comment]
I think Homebridge is about exposing devices that don’t (fully) support HomeKit as HomeKit accessories.  At least, that’s what my plugins do.  Creating new accessories by combining multiple devices is beyond that.

I suppose, technically, you could create a dedicated dhfd plugin for your own use.  Note that Homebridge plugins don’t have access to other HomeKit accessories.  The dhfd plugin would need to use one of the Nuki APIs to check and control the lock state.  And it would need to interact with the relay on the esp8266 (over mttq) to activate the buzzer.

**Comment by nixmeer** [comment]
Hello again,
since I did not find another solution yet, I settled on the idea of using the opener for unlatching. I understand, that combining a Smart Lock with an Opener is not intended by Nuki and adds functionality but I guess that is what homebridge somehow does. Still, when unlatching with the smart lock, the door is pushed open by the force of the seal even if nobody goes through it and remains open afterwards. If instead of unlatching the opener is used and nobody goes through, the door remains closed and can be locked without me closing the door. But in case of the smart lock being in the locked position, the opener needs to wait until the smart lock unlocked the door.

Until now, I only did minor changes to homebridge plugins and got limited experience. After looking into the code, I got some thoughts and questions. I hope you can help me out a little, even though you did not 

If I understand correctly, NbServices is what tells homebridge what to display in the Apple Home App (or eve and so on), and NbAccessory is what connects to device through http and has an instance of the , right? 

My basic idea is to implement it as with the latch: create an "Opener" checkbox in the settings of the plugin and have up to three Lock Mechanisms combined (locking/unlocking, unlatching and opener). I see four options how to implement this:
1. Add a NbService.Opener to the Smart Lock accessory (as done with the latch)
2. Add a NbService.SmartLock to the Opener accessory (as done with the bridge)
3. Add a custom NbService.OpenerToUnlatch to the Smart Lock accessory (in case this opener needs to differ from NbService.Opener)
4. Add a custom NbService.SmartLock to the  Opener accessory (in case this opener needs to differ from NbService.SmartLock)

Do you see any issues with one of the options? Which sounds the easiest? Which one do you prefer?

**Comment by ebaauw** [comment]
In HomeKit-speak, an accessory is a physical device; a service is a logical device, in independent function of a physical device.  Other than room assignment, which is done at the accessory level, HomeKit (as well as Siri) deals exclusively with services.  From a user experience, there's no difference between two services on the same accessory vs two services on different accessories, once you select "show as multiple tiles" in the Home app.

Imho, the smart lock should have been a single service, providing lock, unlock, and unlatch.  Unfortunately, Americans don't understand unlatch, and consequently, HomeKit doesn't support it.  That's why I resort to exposing a second lock mechanism service for it.  Nuki mentioned that they are in the process of adding the unlatch feature to Matter, but I doubt that will be retro-fitted to the HomeKit Accessory Protocol (and thus available to Homebridge).

I think your challenge is not so much how to expose the detached home front door to HomeKit, but how to "link" the door lock and the buzzer: you want to unlock the lock (when locked), before activating the buzzer.  Just exposing an additional service won't do that.  Either you create a new "DHFD" accessory, re-using the existing Homebridge NB services for the smart lock and opener, adding the logic to "link" the services to this accessory, or you simply use the existing Homebridge NB accessories, adding the logic externally, through automation.  As I mentioned above, I think this is feasible in HomeKit, with the help of a dummy switch.

On the odd change that HAP will support unlatch, you could create a single DHFD service, replacing the existing smart lock and opener services, and map the unlatch feature to the buzzer.

Anyway, implementing a DFDH accessory or service in a fork of Homebridge NB will be ugly.  You'll need to configure somehow (in config.json) which devices to combine into the DFDH.

Note that you'll have the same challenge of linking the buzzer and the lock, irrespective of the solution you use for the buzzer, a Nuki Opener or a relay.  With the Opener, you would get the door bell in HomeKit, though.

**Comment by nixmeer** [comment]
Thank you for the reply!

> In HomeKit-speak, an accessory is a physical device; a service is a logical device, in independent function of a physical device. Other than room assignment, which is done at the accessory level, HomeKit (as well as Siri) deals exclusively with services. From a user experience, there's no difference between two services on the same accessory vs two services on different accessories, once you select "show as multiple tiles" in the Home app.

That confirms what I understood from your code and tried to describe above. Thanks for the confirmation!

> Imho, the smart lock should have been a single service, providing lock, unlock, and unlatch. Unfortunately, Americans don't understand unlatch, and consequently, HomeKit doesn't support it. That's why I resort to exposing a second lock mechanism service for it. Nuki mentioned that they are in the process of adding the unlatch feature to Matter, but I doubt that will be retro-fitted to the HomeKit Accessory Protocol (and thus available to Homebridge).

Yes, I share your assessment about the HAP never getting the latch option. I have read about Nuki adding it to matter successfully but that does not mean that Apple is going to implement it into the home app.

> On the odd change that HAP will support unlatch, you could create a single DHFD service, replacing the existing smart lock and opener services, and map the unlatch feature to the buzzer.

I guess that is years away from now and I do not consider that for now.

> I think your challenge is not so much how to expose the detached home front door to HomeKit, but how to "link" the door lock and the buzzer: you want to unlock the lock (when locked), before activating the buzzer. Just exposing an additional service won't do that. Either you create a new "DHFD" accessory, re-using the existing Homebridge NB services for the smart lock and opener, adding the logic to "link" the services to this accessory

That sounds like what I imagined. The new "DHFD" accessory (it took me a while to understand what you you mean by DHFD...) would be just as the SmartLockAccessory with the latch option enabled: One tile with two Lock Mechanisms. The Smart Lock NbService works just as expected. When the buzzer/opener lock mechanism is set to lock action "unlock", the plugin first sets the Smart Lock-NBService to unlock, then waits until the lock state is "unlocked" and then set the opener action to "open".

> Anyway, implementing a DFDH accessory or service in a fork of Homebridge NB will be ugly. You'll need to configure somehow (in config.json) which devices to combine into the DFDH.

This brings me to an idea that is not the most convenient and user friendly but might work. How about a DHFD list (or dict) in the config.json, that has the smart lock's and the opener's nuki id? For the automated discovery, only NbServices are created for devices that are not on the list. For every entry in the list, a DHFD accessory is created, that has a NbService for a Smart Lock and an Opener. I will try to implement the NbAccessory. Are there any issues you see with that?

Thank you so much for helping me to think this through!!
