### ISSUE TITLE
Remove Old Devices

### ISSUE THREAD

**Issue by kloibs** [ebaauw/homebridge-nb#135]
Hi there! I recently removed my Nuki Smart Lock in favor of testing Aqara‘s U200. I wanted to remove the lock while keeping the Nuki Opener being exposed to the plugin. 

I saw issue #110 with this issue and the `removeStaleAccessories` feature, but unfortunately deleting the lock as a cached accessory did nothing aside from merge the latch and lock as one accessory like they were when I initially included the lock.

Will I have to reinstall the plugin? I’d like to avoid this if possible since I just recently reconfigured all my automations recently 🥲

**Comment by ebaauw** [comment]
Did you try setting `removeStaleAccessories` and restarting Homebridge?  Did you double-check that the Nuki bridge no longer reports the removed lock?

Re-installing the plugin won’t affect cached accessories.

**Comment by kloibs** [comment]
Thanks per usual for the support! `removeStaleAccessories` and a restart didn’t do anything. How can I check if the bridge is still reporting it & what’s the recommendation if it does or doesn’t report it?

**Comment by ebaauw** [comment]
> How can I check if the bridge is still reporting 

See https://github.com/ebaauw/homebridge-nb/issues/110#issuecomment-1577129855

If it’s still there, remove it from the Nuki app.  If not set _Log Level_ on the Nuki bridge accessory to 2, run Homebridge in DEBUG mode, and capture and attach the log file.

**Comment by kloibs** [comment]
I don't really have the knowledge to figure out how to see if the bridge is still reporting it or not. I removed it from the Nuki app and thought that would be enough, but I guess not.

I'll just set up the plugin from scratch again. Thanks anyways!
