### ISSUE TITLE
He doesn't see the accessories!

### ISSUE THREAD

**Issue by ApOphisRulez** [ebaauw/homebridge-nb#137]
I installed both the server and the Bridge NB but I don't see any NUKI accessories, not even the OPENER which is what interests me!

**Comment by ebaauw** [comment]
What’s the output of `nb discover`?

Note that the Nuki bridge needs Internet access from the same local IP subnet as Homebridge NB, and discovery must be enabled in the Nuki app.

**Comment by ApOphisRulez** [comment]
> What’s the output of `nb discover`?
> 
> Note that the Nuki bridge needs Internet access from the same local IP subnet as Homebridge NB, and discovery must be enabled in the Nuki app.

In nb discover I have....

`[
  {
    "bridgeId": 1811735430,
    "dateUpdated": "2024-07-27T16:34:48Z",
    "ip": "192.168.178.76",
    "port": 8080
  }
]
`

Uhm... how?
Where is a guide to do this?

I opened from the Nuki app "http...." what else should I do?

**Comment by ApOphisRulez** [comment]
![IMG_2019](https://github.com/user-attachments/assets/e2c5099a-be99-45a7-acd6-86544298488a)
![IMG_2020](https://github.com/user-attachments/assets/a34d58e3-8cb0-4a46-9f81-584396fb30fd)

**Comment by ApOphisRulez** [comment]
Ok... I managed to solve....

Everything works...

Only thing, without it giving me any problems but it reports it to me ....

In the LOG of HOMEBRIDGE it signals me every minute ...

`[7/28/2024, 6:34:41 PM] [Nuki] Nuki_Bridge_6BFCE386: error: too many callbacks registered
[7/28/2024, 6:34:41 PM] [Nuki] Nuki_Bridge_6BFCE386: Last Updated: set to "Sun Jul 28 2024 18:34:43" (from "Sun Jul 28 2024 18:33:43")`

**Comment by ebaauw** [comment]
See #5.
