### ISSUE TITLE
Double Notification for Opener

### ISSUE THREAD

**Issue by namealwaysinuse** [ebaauw/homebridge-nb#138]
Hello,

is there a way to disable the doubled notification for the Opener?

If you press the button I get "opened" and a few seconds later "closed".

Best

**Comment by ebaauw** [comment]
Notifications are handled by Apple’s Home app.  Accessories (incl those exposed by Homebridge plugins) cannot influence these.  Afaik, you can switch (all) notifications for a lock on or off, but there’s no finer-grained control.

**Comment by namealwaysinuse** [comment]
Got it thanks.

Could have been that there is a way to expose the opener different. Then I disable the Notification.

**Comment by ebaauw** [comment]
I’m open to suggestions, but using a _Lock Mechanism_ (and _Doorbell_) seems the best fit to me.  I don’t think HomeKit has actuators with one-way notifications.

**Comment by namealwaysinuse** [comment]
Totally understand! Don't worry. Doorbell and Doorsensor is on a different paper for me... it's just called by the 60 seconds heart beat but the lock is giving push notifications. Its strange cause everything is connected to the hub and there is also just this one callback registered :D
