### ISSUE TITLE
Feature Request -  Enable extra latch for RTO

### ISSUE THREAD

**Issue by namealwaysinuse** [ebaauw/homebridge-nb#139]
Hi,

is it possible to add a function (like the latch one for the lock) to activate "ring to open" via the opener?

Thanks

Best

Edit: maybe its possible now, saw there were some requests a few years ago

**Comment by ebaauw** [comment]
Ring to Open is exposed as custom characteristic.  You need to use a decent HomeKit app, like Eve, to see it, as Apple’s Home doesn’t support all of HomeKit.  To use it in Home or Siri, create a HomeKit scene with the custom characteristic in Eve.

**Comment by namealwaysinuse** [comment]
I saw this, I just thought would be awesome to have it integrated in the widget. 
If I tap the lock I get the view of "unlock" and "unlatch", my opener is directly opening.
The Nuki widget gives the options but everything connected to Nuki via the web api is slow as hell, the opener takes like 10 seconds to respond and my apple home app 2-3 sec.

**Comment by ebaauw** [comment]
Into which widget?

**Comment by namealwaysinuse** [comment]
The default Apple Home widget. There you have a „link“ to your triggers (it basically opens the same menu as in the home app itself, but on opener it opens the door directly 😂

**Comment by ebaauw** [comment]
> The default Apple Home widget.

iOS/iPadOS/macOS widgets are handled by HomeKit itself - accessoires have no influence on that.
