### ISSUE TITLE
[Question] Problem finding the Opener

### ISSUE THREAD

**Issue by LukasM937** [ebaauw/homebridge-nb#14]
Sadly I'm not able to find the Opener.
Thus far the Api is enabled and the Doorlock, Doorsensor and Nuki-bridge where found without any problem.
Could you advise something?

**Comment by ebaauw** [comment]
Is the Opener visible in the Nuki app?  Did you link it to the bridge in the Nuki app?

**Comment by LukasM937** [comment]
Yes it is visible, and works normally with the Nuki app. (There were a few hiccups at the start but now it is fine, also Nuki web is enabled for both

**Comment by ebaauw** [comment]
Did you link it to the bridge in the Nuki app? Is it returned when you issue `nb list`?

**Comment by LukasM937** [comment]
it is linked to the bridge, thus it is accessible via the Nuki web interface, with strong Bluetooth connection. `nb list` asked for a host to be set, how could I do it?

**Comment by ebaauw** [comment]
Issue `nb -h` or `nb --help` for more info.

Issue `nb -H `_host_` -T `_token_` list`, to specify the hostname or IP address and access token of the Nuki bridge.  You can also set `NB_HOST` and `NB_TOKEN` so you don't have to specify them each time you run `nb`.  

Run `nb -H `_host_` auth` to obtain the token (you need to press the button on the bridge).
Run `nb discover` to obtain the IP address of the Nuki bridge.

**Comment by LukasM937** [comment]
Thank you
