### ISSUE TITLE
Suppress second or third unlock when door already has been unlocked very recently

### ISSUE THREAD

**Issue by phis5533** [ebaauw/homebridge-nb#140]
Hello Erik,  thank you for your plugins, very useful !

There is a bad behavior when you arrive more than one person at the same time, the unlock command is sent n times and the lock remain in a status "stuck open" ("bloqué" in French).
And then the Auto-lock doesn't work and the door remains open.
Like describes here : https://developer.nuki.io/t/suppress-second-or-third-unlock-when-door-already-has-been-unlocked-very-recently/1116

Can you do something ? Or did I miss a configuration ?

Regards.
Philippe

**Comment by ebaauw** [comment]
Homebridge NB only knows what other apps and devices are sending to the lock, after the lock reports a state change through the Nuki bridge.  So there's nothing I can do to block commands while commands by others are underway.

Homebridge NB won't send a second unlock (or other) command, until it has received a response from the Nuki bridge, or until a timeout occurs.  The default timeout is 15s, but you can change this in config.json.

**Comment by phis5533** [comment]
Understood.
Thanks for your quick and precise answer !
Have a great day

**Comment by phis5533** [comment]
Topic closed
