### ISSUE TITLE
Inconsistent Latch Behavior with "Unlock" Slider in Apple Home

### ISSUE THREAD

**Issue by petarhristov94** [ebaauw/homebridge-nb#146]
### Issue Description
When using the "unlock" slider in the Apple Home app to unlock, lock, and immediately unlock again, the door is only unlocked but not unlatched. However, if you wait a short period before unlocking again, the door is both unlocked and unlatched.

### Expected Behavior
- Using the "unlock" slider should **only unlock** the door, regardless of timing.
- Using the "latch" slider should **unlock and unlatch** the door.

### Steps to Reproduce
1. Use the "unlock" slider to unlock the door.
2. Lock the door again.
3. Immediately use the "unlock" slider to unlock the door again.
4. Observe that the door is only unlocked and not unlatched.

### Additional Observation
Waiting a few seconds before using the "unlock" slider for the second time results in both unlocking and unlatching, which diverges from the expected behavior.

**Plugin Version**: v1.4.27  
**Configuration Settings**: 
```json
{
    "name": "Nuki",
    "encryption": "encryptedToken",
    "latch": true,
    "platform": "NB"
}

```

**Comment by ebaauw** [comment]
v1.4.29 disables the unlock to unlock to unlatch feature.  I think this should solve this issue.

**Comment by petarhristov94** [comment]
@ebaauw 

Thank you for the clarification and the update!

I can confirm that I am using Apple's Home app on iOS 18 with HomeKit. After updating to v1.4.29, I tested the behavior several times, both with and without delays. The issue seems to be resolved now. Unlocking the door via the "unlock" slider only unlocks the door and does not unlatch it, as expected.

Thanks for addressing this so quickly!
