### ISSUE TITLE
Bridge auto discovery not working, any way to configure manually?

### ISSUE THREAD

**Issue by Domenikus** [ebaauw/homebridge-nb#148]
Hi,

the API from Nuki to discovery Bridges returns forbidden. So I cannot configure my bridge. https://api.nuki.io/discover/bridges
Anyone else having this problem? Any way to configure the bridge manually?

**Comment by ebaauw** [comment]
I can confirm the issue:
```
$ nb discover
nb discover: nuki server: request 1: GET /bridges
nb discover: warning: nuki server: request 1: error: http status 403 Forbidden
nb discover: fatal: http status 403 Forbidden
```

Haven't seen this before.  Afaik, the Nuki bridge doesn't provide local discovery, so this sucks big time.  Currently, Homebridge NB does not support specifying the bridge(s) in config.json.  If the Nuki server remains unresponsive, I might need to change that :-(.

**Comment by ebaauw** [comment]
Opened an issue on the Nuki forum, https://developer.nuki.io/t/nuki-bridge-discovery-broken-server-returns-403-forbidden/31144?u=ebaauw

**Comment by Domenikus** [comment]
Hi,

thanks for the quick response. On on Hand I'm happy that I'm not the only one. Btw using your plugin since year. Worked like a charm ;).

**Comment by ebaauw** [comment]
Once the bridge has been discovered, Homebridge NB persists its IP address in `cachedAccessories` and continues to interact with it.  That is, until the bridge's IP address changes, at which point discovery is needed to find the bridge under the new IP address.

**Comment by Domenikus** [comment]
Nuki endpoint is now available, but really slow.

nb discover -t 60
