### ISSUE TITLE
Question to shutdown of homebridge (too many callbacks registered)

### ISSUE THREAD

**Issue by thecem** [ebaauw/homebridge-nb#15]
How is the right way to shutdown the HB, to prevent "too many callbacks registered"?

I Use a NUC/Win10/HomeAssistant/(Portainer)/(oznu/docker-homebridge).

When I reboot Home Assistant Host System in Supervisor with the build in "reboot" button, then I have an additional callback registered.

Also I tried to reboot in portainer with the reboot button the "oznu/docker-homebridge", then I have also an additional callback registered.

So what would be the preferred solution? Is there something to do in the "oznu/docker-homebridge" container or config, that portainer shutdown the oznu container in the right way?

**Comment by thecem** [comment]
I tried something different: I restarted the docker container oznu/docker-homebridge via:

`docker container restart xxxxvvvvxxxvvv`

an get even an additional callback registration, so it seams that the container even don't the HB sevice in the right way down.

**Comment by ebaauw** [comment]
If you sent a SIGINT or SIGTERM signal to Homebridge, it should shut down gracefully, giving Homebridge NB the time to cancel the callback subscription.  Enable DEBUG mode (and set _Log Level_ to 2) to see the calls Homebridge NB makes to the Nuki bridge.

If you're sending that signal alright, but it doesn't work, there's probably another plugin hijacking the signal and terminating Homebridge non-gracefully.

**Comment by thecem** [comment]
Yes you absolutly right, I readed and tried to understand #9, #10. But I understood after some testing that the oznu/docker-homebridge container don't send the SIGTERM to HB. If HB receives the SIGTERM it cancel the callback subscription. I see this in HB Log.
I tried every possible combination of reboot/kill/stop like:

`docker kill ----signal=SIGQUIT homebridgecontainer`

but the container is immediately shutdown/stpped.

So I opened a Issue on https://github.com/oznu/docker-homebridge/issues/348#issue-786999272

On the other hand, could it be possible to have the callback subscription not every time of reboot renewed, but further more static?

Thanks in advance!

**Comment by thecem** [comment]
Another idea:

hombridge-nb knows the actual subscription, so if hb-nb was not able to remove the subscription on SIGTERM it could be removed on start and replaced with the new one.
Maybe this could be a solution?

**Comment by ebaauw** [comment]
> On the other hand, could it be possible to have the callback subscription not every time of reboot renewed, but further more static?

A whole lot of work: need to handle the case where the port is taken by some-one else in between the Homebridge restarts.

> hombridge-nb knows the actual subscription

While running.  It's currently not persisted between restarts, but it could be.

> hb-nb was not able to remove the subscription on SIGTERM it could be removed on start and replaced with the new one

Might actually work, in most cases.  I don't think this is a Homebridge NB problem, though.

I suggest you run a little script on starting Docker to remove any stale subscriptions by the container.  Assuming
- the container has a fixed IP address `x.x.x.x`;
- the Nuki bridge is at `h.h.h.h`;
- the Nuki bridge token is `tttttt`;
- NodeJS is installed to `/usr/lib` in the container,

The script would be something like:
```
#!/bin/bash
PH_HOST=h.h.h.h
PH_TOKEN=tttttt
alias json=/usr/lib/node_modules/homebridge-nb/node_modules/homebridge-lib/cli/json.js

for id in $(nb callbackList | json -al | grep x.x.x.x | cut -d / -f 3) ; do
  nb callbackRemove ${id}
done
```

**Comment by thecem** [comment]
Assuming the IP is the same for different callbacks id and only the port is different, how to identify the id for the callbackRemove is the right one for hb-nb? Above in the script it will remove every callback entry, that matches the container IP?

**Comment by ebaauw** [comment]
Yes.  Are you running multiple Niki HTTP API clients from the same container?

**Comment by thecem** [comment]
No, not from the same container, but with one bridged network on the same IP. So for the nuki bridge it is only one ip for all api clients...

**Comment by ebaauw** [comment]
I don’t think I can solve this completely in Homebridge NB.  Homebridge only flushes the persistent storage on (clean) exit.  I do flush it every 30 minutes, just to be sure.  However, this writes out the entire `cachedAccessories`, with info from all plugins.  If I flush it more often (after creating a callback subscription), people start complaining about the wear on their uSD card.

I also seem to find that the Nuki bridge has issues when the destination of registered callbacks cannot be reached.  Typically this causes the remaining callbacks to fail as well.  I think it’s bad form to leave the callback in place while the corresponding web server isn’t running.  Imho, your best option really is to find a way to shutdown the container cleanly.

**Comment by ebaauw** [comment]
Hm. it's not as bad as I feared.  The callback Url is fixed when Homebridge NB starts.  Even if the subscription is lost (deleted by some-one else), Homebridge NB re-subscribes using the same callback URL.  Homebridge Lib flushes `cachedAccessories` 30 seconds after Homebridge has started the HAP server, which is more than enough time for Homebridge NB to setup the web server and determine the callback URL.  As long as you don't crash Homebridge or kill the container within 30 seconds, you should be good.

Still not sure about the Niki bridge dealing with undeliverable notifications, though.

**Comment by ebaauw** [comment]
In v1.0.4.

**Comment by thecem** [comment]
I verified the function of this, and in all shutdown and reboot scenarios that are typically for NUC10/WIN10/VirtualBox/HomeAssitannt/Portainer/(Oznu/docker-homebridge) it works for me. So no additionally callback subscriptions!

```
[1/16/2021, 8:35:02 AM] [Nuki] Nuki_Bridge_12345678C: remove stale subscription
[1/16/2021, 8:35:02 AM] [Nuki] listening on http://192.168.6.100:43635/notify
```

Thanks a lot!
