### ISSUE TITLE
Unlatch a lock with slide from unlock to unlock (same like Nuki HomeKit implementation).

### ISSUE THREAD

**Issue by thecem** [ebaauw/homebridge-nb#16]
I could lock and unlock the lock, but not able to unlatch the lock with the lock tile menu.
Is there a possibility to have the same function in place like Nuki it directly provides with the homekit integration:

"slide from unlock to unlock"

Thanks in advance.

**Comment by ebaauw** [comment]
Is that the native HomeKit feature of the Smart Lock or the Nuki app?  Could you provide a screenshot how that works?

if you set `latch` in config.json, Homebridge NB exposes a second accessory with a _Lock Mechanism_ service for the Smart Lock, for unlatching.  It works quite well in the Home app, but Siri starts bitching that there’s more than one lock in the room, so instead of “Hey Siri, unlock the entrance” I need to say “Hey Siri, unlock the entrance door lock in the entrance”.  That’s why I made exposing the latch optional.

**Comment by thecem** [comment]
https://user-images.githubusercontent.com/46648579/104807210-7fe47680-57dd-11eb-9738-0afa1ffd8f72.mov

**Comment by ebaauw** [comment]
Hm, interesting.  Does that also work when quickly flipping the tile twice?

**Comment by thecem** [comment]
So if I slide fast from unlock to lock (without pause or losing touch) and directly to unlock the _Lock Mechanism_ will be unlatched.
I have a push bar outside the door, if the door is closed you are not able to open it.

Never tried to flipping the tile twice, but when then the nuki fully lock and then fully unlock and unlatch the door.

**Comment by ebaauw** [comment]
I need to figure out if HomeKit just sends two changes (lock, unlock) in quick succession, or something special like a single “change” (unlock).

**Comment by ebaauw** [comment]
Did some probing running `DEBUG=* homebridge -D`.

HomeKit sends a single update with value `0` (unlocked) when moving the slider really quickly from _Unlocked_ to _Locked_ back to _Unlocked_.  If I take a just a little bit more time, HomeKit sends two updates, one for `1` (locked) and one for `0`.  I cannot seem to press the tile twice quickly enough for HomeKit to send a single update.

> So if I slide fast from unlock to lock (without pause or losing touch) and directly to unlock the Lock Mechanism will be unlatched.
> Never tried to flipping the tile twice, but when then the nuki fully lock and then fully unlock and unlatch the door.

So it would seem the Smart Lock handles the setting from `0` to `0` by unlatching, but the setting from `0` to `1` and from `1` to `0` as two separate events.  If you just unlock the Smart Lock through its native HomeKit feature, does it also unlatch the lock?  What's the _Choose door fitting_ setting for the Smart Lock?

**Comment by thecem** [comment]
> If you just unlock the Smart Lock through its native HomeKit feature, does it also unlatch the lock? 

The lock unlock and unlatch

> What's the Choose door fitting setting for the Smart Lock?

Lock -> Administration -> Door handle (Türgriff) -> knob and bar (Knauf oder Stange).

The Nuki descriptions says, you will find this only on the German blog page:

With HomeKit, you are able to unlock and lock the door remotely via the Home app. If you have a **knob or a bar** on the outside of your door, **"unlock" always means "open door", because Apple only provides two states for smart locks in the HomeKit protocol**.

**Comment by ebaauw** [comment]
I found something similar in the API documentation (hence my question):

> Possible outcome of a simple lock action (mapping handled in the firmware of the device):

> action | smartlock / knob | smartlock / handle | opener
> -- | -- | -- | --
> /lock | lock | lock | deactivate rto and cm
> /unlock | unlatch | unlock | open

Originally, Homebridge NB worked like that, because it issues a `/unlock`, but I changed that to a `/lockAction` because of #2.  I have a lever, so I never noticed this behaviour earlier.  Still not sure what the "correct" functionality for Homebridge NB would be (always unlock vs unlatch for knob / unlock for lever).

I got the "slide from unlock to unlock" working.  Could you test beta v5.0.5-0?

**Comment by thecem** [comment]
Installed and tested: WOW!
This is really new! For me the best solution right now!


**unlock to unlock: unlatch
unlock to lock: lock
lock to unlock: unlock**
_(and no unlatch!! More secure because no unwanted unlatch the door and possible open doors!)_

For a unlatch automation, the option latch could be ticked.

thank you very much, if you need additional tests let me know...

**Comment by ebaauw** [comment]
Cool.  I was quite pleased exposing the latch as separate _Lock Mechanism_, until I found out that Siri refuses to unlock the door, because it has two locks.  Have been thinking about a custom characteristic to switch between unlock vs unlatch, but that won’t be usable in Home.  The unlock to unlock is quite an ingenious approach.  Only disadvantage: you cannot include this in a HomeKit scene.

For something different: are you using lock ‘n’ go?  Would it make sense to expose that?  If so, how?  Similarly to the ring-to-open on the Opener (using a custom characteristic)?

**Comment by thecem** [comment]
I use it when I leave. Is there a possibility to change this time via api? So it would complement the settings.
I don’t see a use case for activation of lng, in the automation you could lock the door on geofencing. 
But this trigger of the lng could be used to start some leaving automatic, like lights out, shut the roller, check window status, open the car, put the light in the stairwell on, check/enable alarm system, etc..

**Comment by thecem** [comment]
Or start the vacuum robots, so I think the WAF would rise... ;-)
I think I would use this function, but never thought about a use case for what the lng could trigger...
Also something different:
Is there a possibility to get information from the keypad?

**Comment by ebaauw** [comment]
> Is there a possibility to change this time via api?

Not at the moment.  The _Lock 'n' Go duration_, like the _Unlatch duration_, isn't exposed by the Nuki bridge API.  They are documented in the _Advanced Config_ of the Smart Lock's Bluetooth API, so, in theory, Nuki could expose these over the bridge as well.  Creating a Homebridge plugin using the Bluetooth API would also be a theoretical possibility.  I have no experience programming Bluetooth.

HomeKit has _Set Duration_ and _Remaining Duration_ characteristics to indicate after what duration a devices should be switches off automatically.  I use these in Homebridge ZP for the Sonos sleep timer.  I think Home shows these only for _Valve_ services, but Eve shows them on other services as well (as _Default Duration_ and _Remaining_).  I haven't yet tried exposing these on a _Lock Mechanism_.

For smart outlets driving irrigation systems, Homebridge Hue maintains the duration timer.  I suppose I could implement a lock'n'go-like feature in Homebridge NB.  Of course, the Smart Lock would only be locked if Homebridge continues to run and can connect to the Smart Lock.  Not sure I would want to bet my home security on this.

> I don’t see a use case for activation of lng, in the automation you could lock the door on geofencing.
But this trigger of the lng could be used to start some leaving automatic

I was thinking about the other way round: when I tell Siri that I'm leaving, she activates the _Away_ HomeKit scene.  From there, I turn off the lights, turn off the music, and lower my thermostat.  I was thinking about unlocking the entrance door to my apparent as well, but having it lock automatically after me would be nice.  I could also try an automation based on the door sensor to lock the door when _Away_ has been set.

> Is there a possibility to get information from the keypad?

Dunno, don't have one.  As with the timings, the keypad seems to be supported in full only by the Bluetooth API.  The bridge API documentation seems to suggest that only the battery state (critical/non-critical) is exposed on the Smart Lock.  I could maybe expose that as a dummy _Stateless Programmable Switch_ (like the bridge), or set the Smart Lock's _Status Low Battery_ when either the Smart Lock or the Keypad battery is critical.

**Comment by ebaauw** [comment]
In v5.0.5.

**Comment by heikobischoff** [comment]
Hi all! I am a little bit confused about the current implementation. 
By default, the door can be locked and unlocked, right? I tried to unlock-unlock the default trigger, but this does not open the latch for me.
What do you think about implementing a switch in the config to configure the behavior of the unlock action in HomeKit to adopt the HomeKit implementation of Nuki? 
The second slider is an option, but this does not work very well with Siri. My idea is to ask Siri on my Apple Watch to open the front door, but this currently does only unlock, but not open the latch.

**Comment by ebaauw** [comment]
Homebridge NB unlatches the door when HomeKit "changes" the target state from unlocked to unlocked.  The Home app triggers this "change" when you slide from unlock to unlock.  I suppose Siri could also trigger it, when she tries to unlock an already unlocked lock.

> My idea is to ask Siri on my Apple Watch to open the front door, but this currently does only unlock, but not open the latch.

Create a HomeKit scene that unlatches the door (using the second slider), and ask Siri to recall that scene.

> Any idea how to trigger the "open" command twice with Siri?

Never tried this myself, but I suppose you could create a Shortcut which unlocks the lock twice.  Then use Siri to trigger the shortcut.

**Comment by justme-1968** [comment]
just a short question/feedback?

is this still supposed to work? with the ios17 beta I can not get the unlatch if I move the slider very fast from unlocked to locked and back. the lock always closes and opens again.
