### ISSUE TITLE
Permanent "Ring to Open" as a button in homekit

### ISSUE THREAD

**Issue by Bodokan** [ebaauw/homebridge-nb#17]
Dear Erik
It would be great to have a seperate Button in HomeKit to switch on and off the permanent "Ring to Open".
Many thanks ...
Kind regards
René

**Comment by ebaauw** [comment]
The function is already there, but you need to use Eve for that.  Create a scene in Eve if you want to control this from Home.

**Comment by Bodokan** [comment]
Okay cool this is working, but if I switch the "Continous Mode" to ON means the "Opener"-Door is alway open.
Right?
The Button in Homekit shows me the "Opener"-Door is closed. Is this not wrong?

**Comment by ebaauw** [comment]
The Opener doesn’t know whether the door is open or closed.  It only knows whether it’s buzzing the door lock.  Homebridge Hue shows the _Lock Mechanism_ as unlocked while buzzing and as locked when not.  You can set the duration of the buzz in the Nuki app.

As far as I understand, continuous mode simply means permanent ring-to-open.  The Opener buzzes automatically when the doorbell rings.  Normally ring-to-open only works once, it’s reset after the buzz.
