### ISSUE TITLE
Cannot read property 'ringactionState' of undefined

### ISSUE THREAD

**Issue by michije** [ebaauw/homebridge-nb#19]
After getting a replacement opener from Nuki, the new opener seems to throw an exception:
"Nuki_Bridge_XXXXX: warning: heartbeat error: TypeError: Cannot read property 'ringactionState' of undefined"
I already enabled debug- and web mode on the opener, updated node.js, renewed the subscription and re-installed the whole plugin. However, the issue persists. Newest firmwares are also installed. Any help would be appreciated!

**Comment by ebaauw** [comment]
Sorry for this, but some stupid questions first:
- Did you reboot (or power cycle) the Nuki bridge?
- After that, did you restart Homebridge?

If the problem persists, please turn on DEBUG mode in Homebridge, set the _Log Level_ on the Nuki bridge accessory to 2 (using Eve or another HomeKit app), and capture and attach the Homebridge log file.

**Comment by michije** [comment]
Hi,
Thank you for the quick reply. I found the issue accidently by looking at the eve app. It looks like the bridge still thought the old opener exists, even though I deleted it properly. After removing again from the bridge and then power cycling everything, the old opener was gone and with it the error.
