### ISSUE TITLE
Nuki bridge shows error in Eve App

### ISSUE THREAD

**Issue by Bladestar2105** [ebaauw/homebridge-nb#2]
Is there anything I have to do?

![4A8EB090-E4EB-40C1-97EB-6FA0C1ECD68B](https://user-images.githubusercontent.com/55372949/99349090-61c0cf80-289b-11eb-88ae-afddc34822e1.jpeg)

**Comment by ebaauw** [comment]
Could you increase the _Log Level_ to 2 and, after a couple of minutes, capture the Homebridge log into a file and attach that?

**Comment by Bladestar2105** [comment]
Okay here is the log.
[homebridge.log.txt](https://github.com/ebaauw/homebridge-nb/files/5551948/homebridge.log.txt)

**Comment by ebaauw** [comment]
That doesn’t contain any debug messages.  Are you running Homebridge with debug enabled?

**Comment by Bladestar2105** [comment]
I will check tomorrow and upload a new log file.

**Comment by Bladestar2105** [comment]
New log uploaded.
[homebridge.log-2.txt](https://github.com/ebaauw/homebridge-nb/files/5558754/homebridge.log-2.txt)

**Comment by ebaauw** [comment]
Thanks.  Your bridge seems to be running older firmware (v1.17.1) than mine (v2.7.0).  I doesn't report `wlanConnected`, that Homebridge NB evaluates setting _Status Fault_.  Could you try and upgrade the bridge from the Nuki app?

**Comment by Bladestar2105** [comment]
My bridge has the newest firmware. It is just a hardware revision 1 model, look at this: https://developer.nuki.io/t/nuki-bridge-firmware-release-notes-public-releases/2797

I registered my lock and the opener to the Nuki beta program (you can do this too by submit them your serial numbers). Also I have paired a keypad as you mention.

**Comment by ebaauw** [comment]
Thanks for the info.  Other than the firmware version, the API gives no clues on hardware versions.  I also see that `wlanConnected` is missing from the API documentation; I'll include a check whether this attribute is actually reported before setting _Status Fault_.

Not sure I want to use beta software to let me into my apartment.  I'm doing this as a hobby and don't have the (financial) resources to setup a test lab for beta versions.

**Comment by Bladestar2105** [comment]
I just triggered the opener from the home app and this appeared in the log.
Is the UTC time correct?

> [18.11.2020, 14:43:22] [Nuki] Nuki_Bridge_4A443E5F: request 31: GET /info
[18.11.2020, 14:43:22] [Nuki] Nuki_Bridge_4A443E5F: request 31: GET /info?ts=2020-11-18T13:43:22Z&rnr=1230&hash=200cb42112d2a9fb6c7f400538539ac09d3f227f6e953acf708b5ad14d5f3a7f: http status 503 Service Unavailable undefined
[18.11.2020, 14:43:22] [Nuki] Nuki_Bridge_4A443E5F: warning: GET /info?ts=2020-11-18T13:43:22Z&rnr=1230&hash=200cb42112d2a9fb6c7f400538539ac09d3f227f6e953acf708b5ad14d5f3a7f: http status 503 Service Unavailable

**Comment by ebaauw** [comment]
For Germany?  Looks like it’s consistent with the localtime.  I think you’ll see an unauthorised message if the time is off by too much.

The `GET /info` is Homebridge NB polling the bridge.  Do you see more warning or error messages?  I think 503 means the bridge is too busy to accept an API call right now.  Did the opener respond?

**Comment by Bladestar2105** [comment]
My question was if it is normal that the UTC time is shown.

No I don't see more error messages or warnings. But yes the opener responded.

Another question. Is it normal that unlocking the smart lock from home app opens the door? This should not be default I think... In my test it opened the door not just unlocking it.

**Comment by ebaauw** [comment]
I send an unlock command, not an unlatch.  It should behave the same as unlock from the Nuki app.

**Comment by Bladestar2105** [comment]
I tested it again, it opened the door. From the Nuki app it works as expected.

**Comment by ebaauw** [comment]
Odd.  I’m new to Nuki, not sure what’s happening here.  Did the app connect to the lock over Bluetooth or through the bridge?  I think the app connects to the bridge through the Nuki server (at least, that’s what the connection status in the app suggests), whereas Homebridge NB uses the local http API.

**Comment by ebaauw** [comment]
Do you have a knob or a handle for your smart lock?  According to the API documentation, an `unlock` results in unlatch for a smart lock with knob.

**Comment by Bladestar2105** [comment]
When I look in the app it shows first the connection over the Nuki servers.

Hm okay, I have a knob.

**Comment by ebaauw** [comment]
Ok, I'll use `/lockAction` instead of `/lock` and `/unlock`.

**Comment by ebaauw** [comment]
Fixed in v0.0.5.
