### ISSUE TITLE
Error characteristic "heartrate"

### ISSUE THREAD

**Issue by Bladestar2105** [ebaauw/homebridge-nb#22]
Hello,

I receiver this error when starting Homebridge beta 1.3.0.
```
[17.2.2021, 18:59:40] [homebridge-nb] This plugin threw an error from the characteristic 'Heartrate': Characteristic Property `maxValue` was set to 600, but for numeric format uint8 maximum possible is 255 See https://git.io/JtMGR for more info.
```

**Comment by ebaauw** [comment]
Are you on v1.0.7?

**Comment by Bladestar2105** [comment]
Yes, version 1.0.7 and the plugin is a separate child bridge.
Beta of homebridge updatet to 1.3.0-63 but the error remains.

**Comment by ebaauw** [comment]
Could you try and delete the child bridge’s `cachedAccessories.xxxxxxxxxxxx`, substituting the `username` of the child bridge.  Or using the UI, remove the cached accessory for the Nuki bridge (under Homebridge settings).

**Comment by Bladestar2105** [comment]
This doesn't help, the message remains.

**Comment by ebaauw** [comment]
That doesn’t compute.  Did the accessory for the Nuki bridge move to the default room after removing it from cache and restarting Homebridge?

**Comment by Bladestar2105** [comment]
No I had to completely remove the bridge from HomeKit because of the message no response for the devices.
After I have added the bridge again they responded.

**Comment by Bladestar2105** [comment]
Okay I tried again and now it is alright.
Thank you again!
