### ISSUE TITLE
Error when starting Homebridge

### ISSUE THREAD

**Issue by R3xRay** [ebaauw/homebridge-nb#24]
When starting the Homebridge the following error appears from the plugin:
[homebridge-nb] This plugin threw an error from the characteristic 'Heartrate': Characteristic Property `maxValue` was set to 600, but for numeric format uint8 maximum possible is 255. See https://git.io/JtMGR for more info.

**Comment by ebaauw** [comment]
See #22.  Please re-install Homebridge NB.
