### ISSUE TITLE
Major delay

### ISSUE THREAD

**Issue by spadrille2** [ebaauw/homebridge-nb#28]
The home app seems to reveive the information about my Nuki locks very late. I have an automation in the Home app who deactivate my alarm system when i open my door with Nuki. It take between 10 seconds to more than one minute for the Home app to deactivate this alarm system, so, sometimes, the siren turns on. The problem seems to come from the Nuki part because the Home app also shows me the notification that the door has been unlocked very late. But as soon as the notification shows, the alarm system is disabled almost immdiatly. 
Here are some error messages that i have found in my logs : 
[14/03/2021 à 15:11:58] [Nuki] Nuki_Bridge_19FED791: warning: request 4121: error: http status 503 Service Unavailable
[14/03/2021 à 15:11:58] [Nuki] Nuki_Bridge_19FED791: warning: heartbeat error: http status 503 Service Unavailable
Is there something i can do to reduce these delays?

**Comment by ebaauw** [comment]
Double-check the subscriptions made to the Nuki bridge, using `nb callbackList`.  Best make sure Homebridge NB is the first in the list, if not the only one.

If you haven't used `nb` before: run `nb discover` to find the IP address of your Nuki bridge; run `nb -H x.x.x.x auth` to obtain a token; then run `nb -H x.x.x.x -T xxxxx callbackList` or set `NB_HOST` and `NB_TOKEN`, so you don't have to specify these each time.

**Comment by spadrille2** [comment]
I have stopped at the fist step of your guide because i found something weird. Only 4 of my 5 locks are discovered when i use nb discover. But on the Homebridge accessories i see the 5 locks. What is happening there?

**Comment by ebaauw** [comment]
`nb discover` discovers Nuki **bridges**, not smart locks nor openers.  Use `nb list` to see the devices connected to a bridge.

**Comment by spadrille2** [comment]
I mispoked. I have 5 nuki bridges, so i should see them all and not 4.

**Comment by ebaauw** [comment]
So I guess the missing bridge was previously discoverable, causing Homebridge NB to create the accessories for the bridge and connected devices.  These accessories are persisted across Homebridge restarts.

Make sure the missing bridge is configured for discovery in the Nuki app.

**Comment by spadrille2** [comment]
I uninstalled the plugin and cleared the nb caches. Then i installed the plugin again. Now "nb discover" sees all the 5 Nuki bridges. 
I have tried to get the token using "nb -H x.x.x.x auth"
It replied with an error : 

nb -H 192.168.178.93 auth
nb auth: press button on Nuki bridge to obtain token
nb auth: 192.168.178.93: request 1: GET /auth
nb auth: warning: 192.168.178.93: request 1: error: 192.168.178.93:8080: cannot connect: EHOSTUNREACH
nb auth: fatal: 192.168.178.93:8080: cannot connect: EHOSTUNREACH

I searches the API token with anither way thru the Nuki app.
I finally made run the calbacklist are here is what it replies : 

pi@raspberrypi:~ $ nb -H 192.168.178.93 -T HDRK7s callbackList
nb callbackList: 192.168.178.93: request 1: GET /callback/list
nb callbackList: warning: 192.168.178.93: request 1: error: 192.168.178.93:8080: cannot connect: EHOSTUNREACH
nb callbackList: fatal: 192.168.178.93:8080: cannot connect: EHOSTUNREACH

Is that normal?

**Comment by ebaauw** [comment]
EHOSTUNREACH means that the IP address cannot be reached.  Most likely wrong IP address and/or port, or a firewall is blocking the traffic.

**Comment by spadrille2** [comment]
It can't be that the IP is wrong since the acessory works. It works with a big delay but it works. For the same reason i don't think that a firewall coud be the problem beacause it would cause the accessory to not work at all, not to work after a big delay. Am i wrong?

**Comment by spadrille2** [comment]
Also i discovered something else. When i had uninstalled the nb plugin, my other devices worked better. I had some 10 sec delay between turning on a device from the device's app and the moment this accessory's state was modified in Homerbridge. Without the nb plugin, the state modification was almost instant. Also sometimes all my devices showed the "no response" for a few minutes and then they were enable again for a fe minites, then "no response" etc. With the NB plugin, that behaviour never occurs. So, i moves the nb plugin on an isolated child bridge inside Homebridge and now it doesn't cause problems to the other accessories. But the big delay between the unlocking of the doors and the reflected state modification in Homebridge is still there. Maybe this information could help you figured it out what is wrong with the plugin.

**Comment by ebaauw** [comment]
I doubt there’s something wrong with Homebridge NB.  If you think there is, please capture and attach a debug log file (see https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge) and attach you config.json.

Note that the Nuki bridge doesn’t handle load well.  I get errors like the 503 when I have two instances of Homebridge NB concurrently accessing the same bridge.

if the IP address and firewall check out, you probably have an intermittent issue with your network.  EHOSTUNREACH isn’t caused by Homebridge NB; it’s reported by NodeJS when Homebridge NB tries to send a request to the Nuki bridge.

**Comment by spadrille2** [comment]
I only have one instance of Homebridge NB, which connects to 5 Nuki bridges but in the same Homebridge NB.
I don't suspect a problem with my network since every other accessories on Homebridge react instantly when there is a state modification.  The NB plugin is the only one giving me such a delay so i still suspect something going on with it.
I've attached a debug log file. I just kept in it lines related to Nuki. I just made 2 actions who had generated these logs:
1 ) Lock one of my 5 Nukis using the Nuki app. Homebridge reflected the lock state around 12 sec after the end of the locking.
2) Unlock the same Nuki lock using the Nuki app. Homebriddge reflected the lock state around 25 sec after the end of the unlocking.
[homebridge.log édité.txt](https://github.com/ebaauw/homebridge-nb/files/6175962/homebridge.log.edite.txt)

**Comment by ebaauw** [comment]
> I don't suspect a problem with my network

The EHOSTUNREACH indicates a connectivity problem.  If you're sure you specified the correct IP address and port, there is an issue with your network (could be a firewall issue), or with the Nuki bridge (try rebooting it).  Note that the webserver created by Homebridge NB needs to be reachable by the Nuki bridges for the callbacks.

> The NB plugin is the only one giving me such a delay

I don't see any delay **in** Homebridge NB.  Please attach the **full** debug log file (from the start of Homebridge to and including the delay) and your config.json for analysis.  Please indicate which lock on which bridge you control through the Nuki app.

Homebridge NB depends on the Nuki bridge callbacks to report changes to the lock state.  By default it polls the bridge once every 60s to sync the state (in case a callback notification went missing).  You can change this in Eve through the _Heartrate_ characteristic on the bridge accessory.  Note that this increases the load on the Nuki bridge, and might cause more frequent 503 errors.  Note that the Nuki bridge isn't built for load, and doesn't handle multiple concurrent clients well.  My bridge often reports 503 error when I run a second (test) instance of Homebridge NB in parallel.

To monitor the callbacks issued by the Nuki Bridge, run `nb -H x.x.x.x -T xxxx eventlog`.  Note that this will create another callback subscription on the Nuki Bridge (the bridge only supports 3 concurrent subscriptions).  I've seen issues with multiple subscriptions, especially when the callback server for the first subscription isn't reachable.  If the bridge delivers the callback only after a delay, there's nothing I can do.  If there's a delay in between the bridge issuing the callback and Homebridge NB updating HomeKit, there's an issue with Homebridge NB.  In that case, the Homebridge log shows a delay between the `event` message and the `set` message (updating the HomeKit characteristic from the event state).
