### ISSUE TITLE
Ability to know which user open the Smart Lock

### ISSUE THREAD

**Issue by cjournet** [ebaauw/homebridge-nb#33]
Hello,

I use this feature with IFTTT but maybe it can be implemented in your plugin.
I explain the case, in IFTTT you can create a trigger when a specific user open the Lock. For example the User Toto using Keypad to open the lock. And from what I have found for the moment, it's only possible to have it with IFTTT for the moment.

Having this kind of information can help making great scenario, for example if my kids is coming back to the house using the keypad, I can start music or a light etc.

Do you think is possible in the API? Having this information in Homekit with performant app like Controller?

Thanks

**Comment by ebaauw** [comment]
I don't think that information is available thought the Nuki bridge HTTP API?  I don't have any keypad myself, so I cannot check, but maybe it's part of the log?  Can you check the output of `nb getlog` (shortly after unlocking the door lock with a keypad).

You need to specify the Nuki bridge through `-H ` or by setting `NB_HOST` and the token by `-T ` or `NB_TOKEN`; see `nb -h` for help.
