### ISSUE TITLE
No discovery, need manual config

### ISSUE THREAD

**Issue by Tyraenor** [ebaauw/homebridge-nb#34]
Hi,

my bridge is not being discovered for some reason. I can run all HTTP requests manually, so I would like to configure the bridge manually, but I do not know what to enter in the config.

Could you help me out here?

Thank you so much!

**Comment by ebaauw** [comment]
Homebridge NB does not support specifying the bridge(s) manually.

**Comment by Tyraenor** [comment]
Hey,

thanks for the reply. Factory reset did the trick. Now it is working.

Thank you very much!

**Comment by Tyraenor** [comment]
One off-topic thing: How do I disable the doorbell in Eve? Maybe I do not see it, or I am too dumb... But I cannot find it. And there is "programable button event" button called Nuki Bridge, what exactly is that for?

**Comment by Tyraenor** [comment]
Ah! Great to know! Thank you!
