### ISSUE TITLE
Feature request: Add option to disable doorbell if RingToOpen is active

### ISSUE THREAD

**Issue by Tyraenor** [ebaauw/homebridge-nb#35]
Hi,

it would be nice to have the option to suppress the doorbell ring if RTO is active.

Because coming home while the little one is asleep and opening the door with RTO will wake him up, as the doorbell is ringing.

To get inspiration on how to realize this, one may look at https://github.com/lukasroegner/homebridge-nuki as the option is present there.

Basically it creates a variable that indicates the active RTO and if the ringactionState is coming up true, then it just checks if RTO is active and supresses the ring. As soon as RTO is being disabled the variable is set to false again.

If I can assist in any way, please let me know.

**Comment by ebaauw** [comment]
You can disable the doorbell by setting _Enabled_ on the _Doorbell_ service to off in Eve.  Homebridge NB already exposes _Ring to Open_ on the _Lock Mechanism_ service.  You can get the desired functionality through HomeKit automations.

**Comment by Tyraenor** [comment]
Ah I get what you approaching... I did not think of that. I will try that. Thank you for the advice.

**Comment by Tyraenor** [comment]
Too bad, it does not work. RTO is being disabled before the ringactionState changes to true... So this approach does not help. Any other ideas?

**Comment by ebaauw** [comment]
Maybe try to reset _Enabled_ when the Opener switches from _Unlocked_ back to _Locked_?  Or when you open the inside door?

**Comment by Tyraenor** [comment]
I did it with a dummy switch, which switches when the doorbell gets enabled/disabled. This thing I can access with a HomeKit shortcut in which I inserted a 10 sec. delay. That works fine. Not the "perfect" and "clean" solution, but it works. Thank you for your help.

Have a nice day.
