### ISSUE TITLE
Feature request: Door latch only for one lock

### ISSUE THREAD

**Issue by Tyraenor** [ebaauw/homebridge-nb#37]
Hi again,

sorry to bother again.

But is there a way to enable the latch only for one lock? As I have two locks but only one has a latch.

Maybe I do not see the way this is being realized, so I am asking for this.

Thank you in advance.

Cheers

**Comment by ebaauw** [comment]
How did you configure these locks?  The one with the latch as knob vs the one without as lever?  Is there another way to recognise which lock supports latch and which doesn’t?  I really want to avoid having to list each device in config.json.  Nuki seems to think that doors with a knob should be unlatched where doors with a handle should be unlocked, see #2.  Maybe a setting that only exposes the latch on locks configured with a knob?

I’m having mixed feelings about the latch function, it works as intended from the Home app, but renders Siri unusable.  I’ve implemented the slide unlock to unlock on the regular lock for unlatching the door, see #16.

**Comment by Tyraenor** [comment]
Ah okay. Good to know. I do not need Siri for Nuki anyways. 

Maybe it would be a possibility to give the option to set an exclusion for a specific Nuki ID regarding the latch...

**Comment by Tyraenor** [comment]
Hi again,

you could check for `"doorsensorState": 1` as this means, there is no doorsensor activated. Would you see that possible?

**Comment by ebaauw** [comment]
Technically I could.   Not sure if that makes sense semantically.   How would enabling or disabling the door sensor on the Smart Lock relate to the door lock cylinder supporting latch?

Also note that the Smart Lock v1 doesn't have a door sensor.  I think the API simply omits the attribute in that case.

**Comment by Tyraenor** [comment]
Okay, how about to add the possibility to define the value of "latch" as true, or true and after that a JSON array?

As an example:
If the user wants all locks with a latch, just set it to true.

If he/she wants the latch only for a specific lock, then set it to "true, { nukiID }".

This way this setting could be just for the "advanced" user and all other user can just use it as they do now.

**Comment by ebaauw** [comment]
As I said before, I don't want to list the devices in config.json.  I'll see if I can expose a characteristic on the lock, to remove the latch when `latch` has been set.

**Comment by ebaauw** [comment]
Could you try beta v1.1.9-0?  This version exposes an additional _Unlatch_ characteristic to the _SmartLock_ service, irrespective of the config.json setting.  It should work the same as the _Latch_ service, except that it's invisible from Home or Siri.  To use it, use Eve, or create a HomeKit scene in Eve, and recall that from Home or Siri.

If this works, I'll probably retire the _Latch_ service and `latch` setting altogether.

**Comment by Tyraenor** [comment]
This does the trick for me, even better! No accidental unlatching. So for me this can stay like this.

Thank you very much again!
