### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by Bankaifan** [ebaauw/homebridge-nb#38]
Hi,
is there a way to reduce the logging of this messages:
![image](https://user-images.githubusercontent.com/476059/126658613-f5dcc8c1-bbfa-4bc8-9ac6-c4cd9227ca94.png)

All other messages are okay. But these come up every minute without any chance of status.

**Comment by ebaauw** [comment]
Set _Log Level_ to 0.  You need to do this in Eve, as Apple's Home app doesn't support custom characteristics.
