### ISSUE TITLE
Unexpected token  in JSON at position 81

### ISSUE THREAD

**Issue by twistedlogick** [ebaauw/homebridge-nb#39]
After pressing the button on the Bridge to allow the plugin to connect, I get the following messages in the Homebridge log:

[31/08/2021, 20:24:28] [Nuki] Nuki_Bridge_17A1D616: request 5: GET /list
[31/08/2021, 20:24:28] [Nuki] Nuki_Bridge_17A1D616: warning: request 5: error: Unexpected token  in JSON at position 81
[31/08/2021, 20:24:28] [Nuki] Nuki_Bridge_17A1D616: warning: heartbeat error: Unexpected token  in JSON at position 81

This repeats every minute.
No Nuki devices are shown in the Home app/Homebridge apart from the Nuki Bridge.

I have browsed to some of the API pages through a browser with the following results:
My /info:
{"bridgeType": 1, "ids": {"hardwareId": (redacted), "serverId": (redacted)}, "versions": {"firmwareVersion": "2.9.3", "wifiFirmwareVersion": "2.2.0"}, "uptime": 295, "currentTime": "2021-08-31T19:17:55+00:00", "wlanConnected": true, "serverConnected": true, "scanResults": [{"deviceType": 2, "nukiId": (redacted), "name": "Nuki_Opener_1CC8DF02", "rssi": -46, "paired": true}]}

My /list:
[{"deviceType": 2, "nukiId": (redacted), "name": "Cygnet Court Front Entrance DoorG", "firmwareVersion": "1.6.4", "lastKnownState": {"mode": 2, "state": 1, "stateName": "online", "batteryCritical": false, "ringactionTimestamp": "2021-08-31T16:19:46+00:00", "ringactionState": false, "timestamp": "2021-08-31T19:13:12+00:00"}}]

Any ideas what could be causing this?
I have removed the plugin and reinstalled it a few times now to no avail.

**Comment by ebaauw** [comment]
It looks like it chokes on the weird character in the name, that is about position 81, isn't it?  I'm not sure if JSON allows these, even in strings, see https://www.json.org/json-en.html.  I'm just doing native `JSON.parse()`

That's an Opener, isn't it?  What's the output of `nb -DD -H x.x.x.x -T xxxxx list`, substituting IP address and token of the Nuki bridge?

**Comment by twistedlogick** [comment]
Perfect - it was the name of the opener for some reason. I didn’t enter a special character in the name weirdly.
I changed the name to something shorter, now it is displaying correctly in the JSON file correctly. 
Thank you for your quick reply!
