### ISSUE TITLE
ECONNREFUSES

### ISSUE THREAD

**Issue by banjohb** [ebaauw/homebridge-nb#43]
After clean install from homebridge and the plugin i only the see this error:

![6F6C8428-622F-4B9D-9A0B-08A4F73BC90C](https://user-images.githubusercontent.com/33402492/139655302-d571a7be-5606-4f91-82b3-1792ff1a446a.jpeg)

With 100.10.1.54:8080/callback/list?token=XXXXX the result is {"callbacks": []}

Pls help

**Comment by ebaauw** [comment]
Homebridge NB is trying to connect to `0.0.0.0`, where it should be (trying to) connect(ing) to the IP address of the bridge, presumably 100.10.1.54.  What is the output of `nb discover`?
