### ISSUE TITLE
request 4: error: http status 401 Unauthorized

### ISSUE THREAD

**Issue by KoblerS** [ebaauw/homebridge-nb#45]
When I try to connect the Nuki Bridge with Homebridge, I get asked in the console output to press the button on the bridge, when I press the button I'll get the following error:

```
[11/26/2021, 1:53:17 PM] [Nuki] Bridge_13D0CC59: request 4: GET /info
[11/26/2021, 1:53:17 PM] [Nuki] warning: Bridge_13D0CC59: request 4: error: http status 401 Unauthorized
[11/26/2021, 1:53:17 PM] [Nuki] warning: http status 401 Unauthorized
```

Tried it for several times, restarted homebridge, restarted Nuki bridge and double checked that HTTP API is enabled.
Any idea why this is not working?

**Comment by ebaauw** [comment]
Homebridge NB only issues the `/info` request, after it has obtained a token from the Nuki Bridge.  401 indicates that the bridge doesn't accept the hashed token.  I haven't seen that before.  The token is hashed with the current date/time; I suppose this could happen if the system clocks on the server running Homebridge and the Nuki Bridge are out of sync.

Please double-check the system time _and_ time zone on the server running Homebridge and power cycle the Nuki Bridge.

If the issue persist after that, please open a terminal on the server running Homebridge issue:
```bash
nb -DD -H x.x.x.x auth
```
replacing `x.x.x.x` with the IP address of your Nuki Bridge.

Press the button on the bridge and note the token reported the Nuki Bridge.

Next, run:
```bash
nb -DD -H x.x.x.x -T tttttt info
```
replacing `x.x.x.x` with the IP address of your Nuki Bridge and `tttttt` with the token.

That should return a valid response.

If not, run:
```bash
curl http://x.x.x.x:8080/info?token=tttttt
```
again, replacing `x.x.x.x` with the IP address of your Nuki Bridge and `tttttt` with the token.

Note the `currentTime` (in UTC) reported by the bridge vs the system UTC time:
```bash
date -u
```

**Comment by KoblerS** [comment]
So the NB tool login worked but the second info command didn't.
The curl command worked instead.

Log Output:

```
/homebridge # nb -DD -H 192.168.178.112 auth                                                                                                    
nb auth: press button on Nuki bridge to obtain token                                                                                            
nb auth: 192.168.178.112: request 1: GET /auth                                                                                                  
nb auth: 192.168.178.112: request 1: GET http://192.168.178.112:8080/auth                                                                       
nb auth: 192.168.178.112: request 1: response: {"success":true,"token":"******"}                                                                
nb auth: 192.168.178.112: request 1: 200 OK                                                                                                     
******                                                                                                                                          
/homebridge # nb -DD -H 192.168.178.112 -T ****** info                                                                                          
nb info: 192.168.178.112: request 1: GET /info                                                                                                  
nb info: 192.168.178.112: request 1: GET http://192.168.178.112:8080/info?ts=2021-11-26T14:16:51Z&rnr=1461&hash=e4ee6c8265535f96da73*********17a2835f8b58754845d2631d                                                                                                                
nb info: 192.168.178.112: request 1: GET /info                                                                                                  
nb info: warning: 192.168.178.112: request 1: error: http status 401 Unauthorized                                                               
nb info: fatal: http status 401 Unauthorized                                                                                                    
/homebridge # curl http://192.168.178.112:8080/info?token=******                                                                                
{
"bridgeType": 1, 
"ids": {
  "hardwareId": ******, 
  "serverId": 332450905
}, 
"versions": {
  "firmwareVersion": "2.10.4",
  "wifiFirmwareVersion": "2.2.0"
}, 
"uptime": 5133, 
"currentTime": "2021-11-26T14:18:42+00:00", 
"wlanConnected": true, 
"serverConnected": true, 
"scanResults": [
{
  "deviceType": 2,
   "nukiId": ******, 
   "name": "Nuki_Opener_******",
   "rssi": -73,
   "paired": false
}, {
  "deviceType": 0, 
  "nukiId": ******,
  "name": "Nuki_1CA0BEB5",
  "rssi": -37,
  "paired": true
}
]
}                                                                          
```

UTC time is the same on homebridge and Nuki bridge

**Comment by ebaauw** [comment]
> "uptime": 5133, 

You haven't power cycled the Nuki bridge yet?

> UTC time is the same on homebridge and Nuki bridge

To what precision?  Did you setup clock synchronisation for the server running Homebridge?  From the Nuki API documentation:
> A hashed token will only be valid with a sufficiently current timestamp and can not be reused, to prevent replay attacks. So making two calls with the exact same timestamp will only work with different random numbers.

In theory, Homebridge NB could compute the wrong hash, but I would expect way more issues if that were the case.  I would need to see the token and full hash value to double-check that.

**Comment by KoblerS** [comment]
I power cycled the Nuki bridge and still no success. The server running Homebridge is a Synology NAS (Docker) syncing with a NTP timeserver. 

Can I provide you the token through a private message?

**Comment by KoblerS** [comment]
You were right, somehow the NTP synchronisation was not quite right (about 1 minute difference) this caused a wrong hashed token. Thank you very much for your help!
