### ISSUE TITLE
Some issue with the openers name

### ISSUE THREAD

**Issue by crabman42** [ebaauw/homebridge-nb#47]
I get the following issue in the logs with version 1.2.2 on HB 1.3.8. Before my opener was called „Haustür“. Have tried to change to „Haustuer“ but issue persists. Bridge is found.

[37m[12/21/2021, 1:59:58 AM] [39m[36m[Nuki][39m Nuki_Bridge_<censored>: set Last Updated from "Tue Dec 21 2021 01:59:37" to "Tue Dec 21 2021 02:00:36"

[37m[12/21/2021, 1:59:58 AM] [39m[36m[Nuki][39m [33mNuki_Bridge_39DC10EB: warning: heartbeat error: RangeError: : invalid name[39m

[33m[0m[90m at Opener.set name (/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:108:13)[39m[33m[0m[39m

[33m[0m[90m at Opener.set name [as name] (/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/AccessoryDelegate.js:130:16)[39m[33m[0m[39m

[33m[0m[90m at new Delegate (/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:38:15)[39m[33m[0m[39m

[33m[0m[90m at new AccessoryDelegate (/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/AccessoryDelegate.js:45:5)[39m[33m[0m[39m

[33m[0m[90m at new NbAccessory (/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:14:5)[39m[33m[0m[39m

[33m[0m[90m at new Opener (/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:357:5)[39m[33m[0m[39m

[33m[0m[90m at Bridge.addOpener (/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:214:24)[39m[33m[0m[39m

[33m[0m[90m at Bridge.heartbeat (/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:265:22)[39m[33m[0m[39m

[33m[0m[90m at processTicksAndRejections (internal/process/task_queues.js:95:5)[39m[33m[0m[39m

**Comment by ebaauw** [comment]
Looks like the bridge is reporting an empty name for the opener.  What’s the output of `nb list`?  Did you restart the bridge, after changing the opener name?

**Comment by crabman42** [comment]
It's still using “Haustür” internally but interestingly the restart solved the issue. Thanks.

/homebridge # nb -H <ip> -T <secret> list
[
  {
    "deviceType": 2,
    "firmwareVersion": "1.6.4",
    "lastKnownState": {
      "batteryCritical": false,
      "mode": 2,
      "state": 1,
      "stateName": "online",
      "timestamp": "2021-12-21T12:04:40+00:00"
    },
    "name": "Haustür",
    "nukiId": <id>
  }
]

BR
crabman

**Comment by ebaauw** [comment]
The bridge only refreshes some device info on reboot, like name or firmware version.  There's nothing I can do about this.
