### ISSUE TITLE
Nuki_Bridge_3FBBE67E: error: too many callbacks registered

### ISSUE THREAD

**Issue by Kever0901** [ebaauw/homebridge-nb#5]
Hi,

i get this error each time the adapter is calling Nuki Bridge to get updates (each minute).

**Comment by ebaauw** [comment]
This means that Homebridge NB cannot register a callback with the Nuki bridge, to receive notifications.  The bridge only supports three callback subscriptions.  Use `nb callbackList` to see which callbacks have been registered, and `nb callbackRemove` to delete stale subscriptions.

**Comment by Kever0901** [comment]
Thank you! That was it!

**Comment by cstephenmaloy** [comment]
Sorry to bother, how do I run NB callback list in the terminal? I believe I am missing something obvious here and I'm not sure what ><
Many thanks

hoobs@hoobs:~$ nb
nb: fatal: parameter command missing
usage: nb [-hVD] [-H hostname[:port]] [-T token] [-t timeout] command [argument ...]
hoobs@hoobs:~$ nb callbackList
nb: fatal: Missing host.  Set NB_HOST or specify -H.
hoobs@hoobs:~$ -h

**Comment by ebaauw** [comment]
`nb -H x.x.x.x -T token callbackList`, substituting the IP address and API token of the Nuke bridge.  Use `nb discover` to find the IP address, and `nb -H x.x.x.x auth` to obtain the token (after pressing the button on the bridge), or look it up in the Nuki app.

**Comment by cstephenmaloy** [comment]
thank you, that's brought me to the below. 
hoobs@hoobs:~$ nb -H x.x.x.x -T (token) callbackList
nb callbackList:x.x.x.x: request 1: GET /callback/list
nb callbackList: warning: x.x.x.x: request 1: error: connect ECONNREFUSED x.x.x.x:8080
nb callbackList: fatal: connect ECONNREFUSED x.x.x.x:8080

**Comment by Blandwehr** [comment]
Where I can find the token?

**Comment by Blandwehr** [comment]
That doesn´t work for me

hoobs@hoobs:~$ nb -H x.x.x.x -T (token) callbackList
nb callbackList:x.x.x.x: request 1: GET /callback/list
nb callbackList: warning: x.x.x.x: request 1: error: connect ECONNREFUSED x.x.x.x:8080
nb callbackList: fatal: connect ECONNREFUSED x.x.x.x:8080

**Comment by pillemats** [comment]
merry Christmas at all :-)

I got this error 

root@homeassistant:/homebridge# nb -H 192.168.178.100 -T xxxxxx callbackRemove         
nb callbackRemove: fatal: parameter id missing
usage: nb callbackRemove [-h] id
root@homeassistant:/homebridge# 

what is the problem?

**Comment by kloibs** [comment]
Hi all, I've tried following some of the steps mentioned here regarding clearing the callbacks with no success. I'm trying the following in terminal:

nb -H [IP address] -T [API token] callbackRemove

I appreciate any and all help!
