### ISSUE TITLE
Changing IP error

### ISSUE THREAD

**Issue by Jordenjj** [ebaauw/homebridge-nb#50]
Hello, after setting a static IP for the bridge, homebridge cannot reach it anymore because its trying to connect to old IP. How do if force this update by rediscovering?

**Comment by ebaauw** [comment]
Homebridge NB should pick up the new IP address as the bridge publishes this to the Nuki discovery service.  Make sure that that’s enabled on the bridge.  Check with `nb discover` that the bridge is discoverable.

**Comment by Jordenjj** [comment]
Wow, problem fixed itself after a certain timeout. Thank you!

**Comment by ebaauw** [comment]
It’s a pity they don’t support local discovery; that’s usually faster and doesn’t depend on some service in the cloud.
