### ISSUE TITLE
Doorbell isn’t Ringing on Homepods

### ISSUE THREAD

**Issue by Zwitschert** [ebaauw/homebridge-nb#52]
I have multiple HomePods and a Nuki Opener which is connected over Nuki Bridge and Homebridge.
Everything is updated to newest version (Homebridge, NB plugin, HomePods {15.3})
In eve app i can see Doorbell is enabled and gets an new timestamp on Last Updated if someone is ringing. But the HomePods aren’t ringing.
If I tap on the endabled switch my Homebridge log says:
[28/01/2022, 12:05:09] [Nuki] Flur Opener: Enabled changed from true to false
[28/01/2022, 12:06:43] [Nuki] Flur Opener: Enabled changed from false to true

In my home app under settings/doorbell i also can’t see the Nuki opener.

Please help ;) i loved this feature

**Comment by ebaauw** [comment]
If _Last Updated_ is updated and the button bounces in Eve, Homebridge NB is doing what it's supposed to do

I didn't get a notification on my Apple devices either when my doorbell rang yesterday.  I didn't look into it, but now I fear this might be a "feature" of iOS 15.3.  Like the _Volume_ and _Microphone_ services, Apple seems to support _Doorbell_ only on video doorbell accessories.  Even before iOS 15.3, you weren't able to attach an action to _Doorbell_ button in Home, but at least you got notifications.

I'm not sure if I can fix the _Doorbell_.  Documentation is severely lacking; I would need to try several combinations of accessories and services for the Opener, hoping that one will re-introduce the notifications.  I don't hold high hopes that this would succeed.

Exposing a video doorbell with a blank image seems a bit too much for my taste, assuming I would get that to work in the first place.  I haven't messed with HomeKit cameras nor video doorbells before.  I think HomeKit links a motion sensor to a video doorbell, if they're in the same room; maybe putting the Opener in the same room as a camera or video doorbell would do the trick.

I could "unlock" the _Lock Mechanism_ service for the Opener when the bell rings, so you'd get a notification (although semantically weird) on your other Apple devices, but not on your HomePod.

**Comment by Zwitschert** [comment]
Thanks for your quick reply.
I get an notification that the bell was ringed (sometimes, today once)
My opener is in a room where a camera, some motion sensors and a presence sensor are.
Apple says in their help that if you have a doorbell every homepod has a switch for doorbell ringing.
It would be very cool if you can reactivate this feature but I understand that this would be a bunch of work.
Otherwise
Thank you for your work and your great plugin!

**Comment by ebaauw** [comment]
Just got a notification on my Mac, iPad, and iPhone (all on latest OS) that the doorbell rang.  Wasn't near my HomePod, so couldn't check that.  Maybe just a hiccup in iCloud, handling the push notifications?

**Comment by mkunzmann** [comment]
Had a similar issue a couple of weeks ago after moving the HomePods to a new wifi. Notifications on the phones were incoming for the doorbell, but HomePods did not ring.
A few days later HomePods started ringing again without me touching anything.

**Comment by ebaauw** [comment]
My HomePod mini is ringing once again.  As far as I cal tell, it was just a hiccup in iCloud.
