### ISSUE TITLE
Ring to open and continuos mode inside Home app

### ISSUE THREAD

**Issue by redeemer666** [ebaauw/homebridge-nb#53]
Hello,

First and foremost, great plugin :-). I’m here to ask why the ring-to-open and continuos mode on the opener are not appearing in the official home app but only in Eve. I don’t use the second one, there is a way to make this 2 functions visible in the standard Home app?

**Comment by ebaauw** [comment]
You’ll have to ask Apple…

The workaround is to create a HomeKit scene in Eve, which you can recall from Home and/or from Siri.
