### ISSUE TITLE
Error 503 on secondary bridge

### ISSUE THREAD

**Issue by redeemer666** [ebaauw/homebridge-nb#54]
Hello,

I have 2 bridges in my setup. The first one worked just fine but I’m not able to configure the second bridge. If I push the button nothing happens and after some time (about 30 minutes) your plug-in is starts to “spam” 503 messages on the second bridge (it asks to press the button but immediately report error 503). Do you know why this happens?

**Comment by redeemer666** [comment]
Oh and one more thing. If I launch the terminal command “nb auth” it asks to press the button, if i press it it gives me the code but still in “home” app is not appearing

**Comment by ebaauw** [comment]
Make sure the HTTP API is enabled on the second bridge.  If `nb auth` obtains a token, I suppose it is.  I don't know why Homebridge NB wouldn't get a token when `nb auth` does.  Both share the same code to communicate with the Nuki bridge.

Please list the full error message next time.  I think it's HTTP status code 503, Service unavailable.  In that case, the Nuki bridge reports that it cannot handle the request.  It overloads rather easily, especially if multiple clients connect to it simultaneously.  I'd restart or power-cycle the bridge, and disable other clients while Homebridge NB is starting.

**Comment by redeemer666** [comment]
Hi @ebaauw,

It looks like it was a misconfigured item in my LAN setup (I have a mesh wi-fi). The RIP was enabled, and this caused the communication error between your plug-in and the bridge. I was able to get the command line to work because when i tested it I was on the same wi-fi satellite of the bridge (my Pi with homebridge is connected on the main router).

Anyway, disabled the RIP and solved the issue.

Thanks for your help.
