### ISSUE TITLE
Disable doorbell notification on geofence RTO

### ISSUE THREAD

**Issue by timgrewe** [ebaauw/homebridge-nb#55]
When I press my doorbell with RTO activated through Nuki's geofencing, I still get the doorbell notification through HomeKit. I haven't been able to replicate this with RTO manually enabled but I haven't tested this extensively.

Is this a bug or expected behaviour?

**Comment by ebaauw** [comment]
HomeKit notifications are handled by Apple in iCloud, and configured through the Home app.  HomeKit accessories don't even know about them, let alone that they can influence them.

Homebridge NB fires the _Doorbell_ service's _Stateless Programmable Switch_ when the Opener reports a `ringActionState`.  I don't really use RTO myself, but I if the Opener still rings in RTO mode, this is to be expected.

I could probably add a _Mute_ option not to fire the _Doorbell_, ignoring the `ringActionState`, but this would be an all-or-nothing setting: as I said before: an accessory cannot selectively enable or disable HomeKit notifications.

**Comment by timgrewe** [comment]
I see. But couldn't the Doorbell's Stateless Programmable Switch only be fired if the Opener reports `state = 1` (i.e. `online`) in its callback?

**Comment by ebaauw** [comment]
> I could probably add a _Mute_ option not to fire the Doorbell, ignoring the `ringActionState`, but this would be an all-or-nothing setting: as I said before: an accessory cannot selectively enable or disable HomeKit notifications.

I already expose _Enabled_ on the _Doorbell_ service for this.

> But couldn't the Doorbell's Stateless Programmable Switch only be fired if the Opener reports "state": 1 (i.e. online) in its callback?

No, just clear _Enabled_ when setting RTO, and set _Enabled_ when clearing RTO.  You could even create a HomeKit automation to do this automatically when changing RTO.

**Comment by sercontri** [comment]
> I could probably add a _Mute_ option not to fire the _Doorbell_, ignoring the `ringActionState`, but this would be an all-or-nothing setting: as I said before: an accessory cannot selectively enable or disable HomeKit notifications.

+1
