### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by sercontri** [ebaauw/homebridge-nb#59]
Could it be possible in the future to put the Bridge as an independent bridge without it appearing in the rooms?

**Comment by ebaauw** [comment]
Short answer: no.

Long answer: you cannot bridge a bridge accessory, so it would have to be an external (non-bridged) accessory, that you need to pair to HomeKit separately from the Homebridge bridge accessory.  Homebridge supports external accessories (e.g. for TVs, that cannot be bridged either), but provides only limited functionality for these.  It does not support accessories bridged by an external bridge accessory at all.  So either Homebridge would need to be enhanced to support this, or the plugin would need to duplicate the Homebridge functionality.  I won’t be doing the latter in my plugins.  I still dream about the former, but I won’t have the time to work on that in the foreseeable future.
