### ISSUE TITLE
How to remove devices from home app after uninstalling plugin?

### ISSUE THREAD

**Issue by martin0675** [ebaauw/homebridge-nb#6]
At first let me say thank you for this plugin. It solves my problem of having more than one Nuki bridge. And it works with automatic detection...really cool!
After testing the plugin I uninstalled the plugin and deleted the part in the config. After restart the devices are still there.
Could you give advice please how to remove them?

Do you plan to support "open" in addition to latch/unlatch? Right now I just can latch/unlatch with Nuki 2.0 but not open the door. Other plugins use 2 switches for this topic.

Thank you again for your work!

Martin

**Comment by ebaauw** [comment]
> At first let me say thank you for this plugin. It solves my problem of having more than one Nuki bridge.

Does it work correctly with multiple bridges?  I designed it for that, but I only have one bridge, so I cannot test it.

> After restart the devices are still there.

What version of Homebridge are you using.  They changed Homebridge to remove stale accessories by default (unless you start Homebridge with `-K`).  For older versions you had to start Homebridge with `-R`.

> Do you plan to support "open" in addition to latch/unlatch?

I think you mean: "in addition to lock/unlock"?  The API actually refers to "open" as "unlatch", there's no mention of "latch".  In older versions, Homebridge NB would actually unlatch the lock when configured with a knob or bar as door fitting.  I changed that in v0.0.5, see https://github.com/ebaauw/homebridge-nb/issues/2#issuecomment-729868458.  Technically, I can send the command (`nb lockAction `_id_` 0 3` should do that already); I'm just not sure how to expose it to Homebridge.  As another _Lock Mechanism_ that resets to _Locked_ (similar to the Opener)?  
I also haven't looked yet at _Lock 'n' Go_ / _Lock 'n' Go with Unlatch_.  Not yet sure how to expose these either.

**Comment by martin0675** [comment]
Dear Erik,
thank you for support.

> Am 02.12.2020 um 17:54 schrieb Erik Baauw <notifications@github.com>:
> 
> 
> At first let me say thank you for this plugin. It solves my problem of having more than one Nuki bridge.
> 
> Does it work correctly with multiple bridges? I designed it for that, but I only have one bridge, so I cannot test it.
> 
> 

Yes, it works fine, automatically with 2 bridges.
> After restart the devices are still there.
> 
> What version of Homebridge are you using. They changed Homebridge to remove stale accessories by default (unless you start Homebridge with -K). For older versions you had to start Homebridge with -R.
> 
> 

I use HOOBS version 3.3.1 (newest). As you can see in the picture the 4 devices still exist. What can I do?
> Do you plan to support "open" in addition to latch/unlatch?
> 
> I think you mean: "in addition to lock/unlock"? The API actually refers to "open" as "unlatch", there's no mention of "latch". In older versions, Homebridge NB would actually unlatch the lock when configured with a knob or bar as door fitting. I changed that in v0.0.5, see #2 (comment) <https://github.com/ebaauw/homebridge-nb/issues/2#issuecomment-729868458>. Technically, I can send the command (nb lockAction id 0 3 should do that already); I'm just not sure how to expose it to Homebridge. As another Lock Mechanism that resets to Locked (similar to the Opener)?
> 
Please have a look at other attachment. For the moment it only moves the „Riegel“ but not the „Falle“.
May be that could help in comparison: I use https://www.npmjs.com/package/homebridge-nukiio with the option „"usesDoorLatch" : true, // (default: false)“ for locks. Then I get an additional switch:  One for moving the „Riegel“ (like your plugin), a second for opening the door what means open the „Riegel“ (if closed) AND pull the  „Falle“.
> I also haven't looked yet at Lock 'n' Go / Lock 'n' Go with Unlatch. Not yet sure how to expose these either.
> 
> 

I also didn’t use that feature until now.

**Comment by ebaauw** [comment]
> I use HOOBS version 3.3.1 (newest). As you can see in the picture the 4 devices still exist. What can I do?

I don’t know.  Please contact HOOBS support.

Pictures are missing?

**Comment by ebaauw** [comment]
The latch seems to be working fine, but Siri tends to get confused by the multiple _Lock Mechanism_ services.  I'll add a `latch` parameter to config.json to enable the second service.  Default disabled.
