### ISSUE TITLE
Doorbell Switch No Reaction

### ISSUE THREAD

**Issue by sewshoetz** [ebaauw/homebridge-nb#61]
Hello ebaauw,

i´ve installed your plugin homebridge-nb, first of all, thanks for your great work!

May i ask you something, concerning the opener-bell-service:
I wanted to trigger a automation, when someone rings the bell.
The plug in shows up in the devices section (screenshot attached), but when i ring the bell, the switches don´t change in any form.
What i´m wrong about, could you give me some advice, how to make it happen, that the switch reacts when someone rings the bell outside, which is connected to the opener?

Would be nice, perhaps it´s an rookie-error, me as newbie could take the blame on me ... :)

Thanks in advance,
Greets from Vienna,
Johannes
![Uploading Bildschirmfoto 2022-03-19 um 12.29.46.png…]()

**Comment by ebaauw** [comment]
No image?

Note that you need an AppleTV, HomePod or iPad as home hub for automations to work.

The doorbell accessory has a _Doorbell_ service with a _Programmable Switch Event_ characteristic, which can be used to trigger automations alright.  Somehow the Home app doesn't show this, but you should be able to select it as a trigger in Eve.  Note that it only supports _Single Press_, even though Eve incorrectly shows _Double Press_ and _Long Press_ as well.

**Comment by sewshoetz** [comment]
Hello Erik, 

thanks for your quick and helpful answer, now i could figure out and detect the programmable switch event (which was kind of hidden, for me as newbie ... ). 

I now built it in as a trigger, and it seems to work, thank you! 
(I´m already using three homepod minis as hub)

Greets, Johannes

**Comment by ebaauw** [comment]
Notifications are handled by Apple; the accessory I.c. a Homebridge plugin, cannot influence them.  You can set _Enabled_ to false to prevent notifications, but that will also prevent the automations.

**Comment by sewshoetz** [comment]
ok, erik, thanks for the fast answer!
still a nice plugin!
