### ISSUE TITLE
Bridge doesn't connect due to error: http status 401 Unauthorized

### ISSUE THREAD

**Issue by al3xzo** [ebaauw/homebridge-nb#62]
<img width="972" alt="Bildschirmfoto 2022-04-06 um 01 28 09" src="https://user-images.githubusercontent.com/79316896/161867410-16a0c484-1c92-426b-9c05-493dbebf9993.png">

**Comment by ebaauw** [comment]
Did you press the button on the bridge?

**Comment by al3xzo** [comment]
Hello Erik,

Yes I did. I restarted Homebridge several times, waited for the bridge to light up and pressed the button. Then the error message (error 401) occurred. 


Best

Alexander Zöchling

**Comment by ebaauw** [comment]
Is the system clock on the server running Homebridge correct?  The Nuki bridge API hashes the token combined with the current time to guard against replay attacks.  If the client (Homebridge) and Nuki bridge clocks are out of sync, the bridge won't accept the request.

**Comment by al3xzo** [comment]
Hello,

you were correct. The container was set to the right time zone, but my server was set incorrectly. I corrected the mistake - nevertheless I couldn’t connect my nuki devices. Now homebridge puts out the following: “error: 0.0.0.0:8080: cannot listen: EADDRINUSE”


Mit freundlichen Grüßen 

Alexander Zöchling

**Comment by ebaauw** [comment]
EADDRINUSE means that the port cannot be opened, because another process already uses it.  This typically happens if you try and start another instance of Homebridge, while it’s already running.
