### ISSUE TITLE
Receiving notification of opener even it doesn’t come from us

### ISSUE THREAD

**Issue by abaozang** [ebaauw/homebridge-nb#65]
Hi,

after installing the plug-in, I started to receive push notifications on every device Inclusive HomePods even when none of our family has rung the door.
Is there any option to filter those ones which don’t come from us?

thanks for the work!

**Comment by ebaauw** [comment]
No.  Nuki doesn’t know who rings the doorbell and Apple doesn’t provide any means to limit doorbell notifications.  You can turn off _Enabled_ on the Opener’s _Doorbell_ service to prevent Homebridge NB from forwarding the doorbell ringing to HomeKit, disabling all notifications.
