### ISSUE TITLE
Noisy log

### ISSUE THREAD

**Issue by distantnative** [ebaauw/homebridge-nb#66]
Awesome plugin, thanks for the great work!

One little thing that is a bit annoying is how many log entries the plugin produces (and drowns out all the important one from other plugins). Any way to disable log entries such as this?

> Nuki_Bridge_69700C9B: set Last Updated from "Sat May 07 2022 11:51:33" to "Sat May 07 2022 11:52:33"

Thanks!

**Comment by ebaauw** [comment]
In HomeKit, set _Log Level_ to 0 on the bridge accessory.

**Comment by distantnative** [comment]
Thanks - for anyone else stumbling across this: the setting is not exposed in Apple's Home app but third-party HomeKit apps
