### ISSUE TITLE
New Feature Request: "Latch Only"

### ISSUE THREAD

**Issue by floriangrotz** [ebaauw/homebridge-nb#68]
I´m ok so far with the Nuki HomeApp Integration. I would be "only" interested in the Latch Mechanism. 
Would be cool if there would be an option in the Setting Menu to be able to "disable" the check box for the Lock. 

Thank you!

**Comment by ebaauw** [comment]
Not sure what you mean by the "check box for the lock"?  I won't be providing an option to expose only the _Lock Mechanism_ service for the latch, if that's what you're asking.  I don't think it's a good idea to combine Homebridge NB with the Smart Lock's native HomeKit integration; neither the Nuki bridge nor the Smart Lock like concurrent connections.

You can unlatch the lock through the native HomeKit integration by "slide from unlock to unlock", see #16.
