### ISSUE TITLE
Option to disable Doorbell

### ISSUE THREAD

**Issue by sftsk** [ebaauw/homebridge-nb#7]
Hello @ebaauw, thanks for the great plugin!

It works really well and is easy to set up.

I do have a problem with the Doorbell service, as it won't show up in the Home app as discussed in #1 it's impossible to disable it. It's a nice feature in theory but as I have multiple HomePods in my home they now all start ringing when somebody rings the bell and I can not disable that anywhere.

Any idea if you can expose the service in a way so it's possible to disable the ringing on the HomePods or if that's too difficult add an option to not set up the Doorbell service?

Thank you for your time.

**Comment by ebaauw** [comment]
> Any idea if you can expose the service in a way so it's possible to disable the ringing on the HomePods

I'd love to, but don't know how.

**Comment by sftsk** [comment]
Ok, thanks for the feedback. Will see if I might have time to take a look eventually.

**Comment by thecem** [comment]
In the HB Nest Cam plugin for the Nest Hello it should be be implemented, maybe you find it in the code:

![AE8104AC-498A-4A8A-A60E-5D87375A375A](https://user-images.githubusercontent.com/46648579/104650383-67c60780-56b6-11eb-8d2e-bfa572af8a02.jpeg)

**Comment by ebaauw** [comment]
That's not going to help.  The issue is that Home only seems to support the _Doorbell_ service in a video doorbell accessory, see #1.

**Comment by thecem** [comment]
So maybe there must be a config entry to disable or ignore this from the API.

**Comment by ebaauw** [comment]
Best I can do is a setting not to update the _Stateless Programmable Switch_ characteristic in the _Doorbell_ service.  That way it won't ring the HomePods, but it won't show an alert on your iPhone either.

Looks like the Nest Cam plugin simply doesn't expose the _Doorbell_ service with that config setting.

**Comment by thecem** [comment]
Yes this would be nice if the user had the choice.

**Comment by ebaauw** [comment]
Version 1.0.3 exposes _Enabled_ on the _Doorbell_ service.  Set this to _Off_ in Eve, to prevent the doorbell from triggering.

**Comment by thecem** [comment]
How nice is this! Unbelievable! So fast! Thanks a lot!
Now the user can disable the doorbell in eve app!
I tried it and it works like a charm!

Thank you very much!
