### ISSUE TITLE
Opener not appearing in Home app; only 2 entries in log under NB

### ISSUE THREAD

**Issue by heynowskippy** [ebaauw/homebridge-nb#72]
Trying to set up NB for first use. All that appears in the Homebridge log from NB are:
`[6/20/2022, 2:39:07 PM] [Nuki] hardware: iMac (Retina 4K, 21.5-inch, 2019)`
`[6/20/2022, 2:39:07 PM] [Nuki] os: macOS Monterey 12.4.0 (21F79)`
What am I missing here?

**Comment by ebaauw** [comment]
there should be more, at least an ID message for the plugin version and a message to press the button on your Nuki bridge, so Homebridge NB can obtain the API token.

What is the output of `nb discover`?  Does it list your Nuki bridge?  And after you power-cycle the bridge?  If still not, make sure the API is enabled and it can connect to `api.nuki.io` to announce its existence and Homebridge NB can discover it (unfortunately, Nuki does not provide local discovery).

**Comment by heynowskippy** [comment]
> What is the output of `nb discover`? Does it list your Nuki bridge? And after you power-cycle the bridge? If still not, make sure the API is enabled and it can connect to `api.nuki.io` to announce its existence and Homebridge NB can discover it (unfortunately, Nuki does not provide local discovery).
`nb discover` returns `[]`, even after power-cycling the Bridge. Can you clarify which API should be enabled? There's the one in Nuki Web, and there's the HTTP API in the app. Both are active. Here's what I've got in the app
![IMG_9449](https://user-images.githubusercontent.com/60857669/175513955-a4ea3dee-3171-48f0-8704-74bf8f763d41.jpg)
:
