### ISSUE TITLE
No accessory visible after initial installation

### ISSUE THREAD

**Issue by bondskin** [ebaauw/homebridge-nb#73]
Hi,

I have installed the plugin and it appears to be working correctly, however no accessory is showing up in my Homekit

Where is my mistake please?
Also the child bridge is not visible in Homekit
API is enabled in the Nuki Web app

[03/07/2022, 09:36:43] [Nuki] Initializing NB platform...
[03/07/2022, 09:36:43] [Nuki] Initializing child bridge 0E:E9:0B:A1:2A:12
[03/07/2022, 09:36:45] [Nuki] Loaded homebridge-nb v1.2.8 child bridge successfully
[03/07/2022, 09:36:45] Loaded 0 cached accessories from cachedAccessories.0EE90BA12A12.
[03/07/2022, 09:36:45] [Nuki] homebridge-nb v1.2.8, node v16.15.1, homebridge v1.5.0, homebridge-lib v5.6.1
[03/07/2022, 09:36:45] Homebridge v1.5.0 (HAP v0.10.2) (Nuki) is running on port 35621.
[03/07/2022, 09:36:45] [Nuki] hardware: Raspberry Pi 4B 1.1 (2GB)
[03/07/2022, 09:36:45] [Nuki] os: Raspbian GNU/Linux 10 (buster)
[03/07/2022, 09:36:45] [Nuki] warning: recommended version: homebridge v1.4.1
[03/07/2022, 09:36:45] [Nuki] Launched child bridge with PID 27997

        {
            "name": "Nuki",
            "latch": true,
            "platform": "NB",
            "_bridge": {
                "username": "0E:E9:0B:A1:2A:12",
                "port": 35621
            }
        }

**Comment by ebaauw** [comment]
Did you pair the child bridge with HomeKit?

**Comment by bondskin** [comment]
Damn... thanks @ebaauw , very valid point.
No, I did not.
But I cannot see a QR or setup code anywhere in the HB log

**Comment by bondskin** [comment]
So bridge paired, thanks!
But still no devices
![IMG_1714B4751ABC-1](https://user-images.githubusercontent.com/55050117/177035869-0968454e-4a9e-454a-80bb-acf963ead57b.jpeg)

**Comment by bondskin** [comment]
pi@raspberrypi:~ $ nb discover
[]

**Comment by bondskin** [comment]
There was also no opportunity / message yet, to push the button on the bridge.

**Comment by ebaauw** [comment]
Make sure the bridge is discoverable and the API is enabled in the Nuki app.  Power cycle the bridge.  Make sure there's no firewall blocking access from the bridge to the Nuki discovery server.

**Comment by funky0888888** [comment]
Hi 
same issue after reinstalling my homebridge.
The nuki bridge is not discovered under 1.5.0

**Comment by bondskin** [comment]
Not sure what "API is enabled in the Nuki app" means? I have enabled the API in the Nuki web but this does not have any effect.
Restarting the Bridge does also not help.
Restarting HB has no effect.

**Comment by ebaauw** [comment]
In the Nuki app, go to _Manage My Devices_, select _Bridge_, select your bridge, hold the button on the bridge as instructed to get to the map showing the _Bridge_ and connected devices.  Press on the bridge to go to the bridge settings.  Make sure _API Quick Discovery_ and _HTTP API_ are enbled, and press _Save_ to save the settings.  Then _Done_ to reboot the bridge.

After that, `nb discover` should find the bridge.  If not, there's probably an issue with your Internet connection or firewall.

**Comment by funky0888888** [comment]
Thanks for helping!

**Comment by bondskin** [comment]
Dear @ebaauw ,

Thank you for the instructions.
Indeed the HTTP API option was disabled, following your instructions I was able to complete the setup.
