### ISSUE TITLE
Two Nuki Bridge

### ISSUE THREAD

**Issue by jorgegp93** [ebaauw/homebridge-nb#75]
Hi,

First of all, thanks for your work, it's amazing to be able to have all the Nuki gadgets in HomeKit.

I have a Nuki Bridge paired with a Nuki Opener, Nuki Door Sensor and Nuki Smart Lock and everything works perfectly in Homekit with Homebridge.

The problem is that, in the same house, I have another Nuki Bridge paired with another Nuki Smart Lock, but don’t appear in Homekit.

Is it possible for the plugin to detect several Nuki bridges?

Thank you in advance,

**Comment by ebaauw** [comment]
Homebridge NB should be able to handle and support multiple Nuki bridges.  Make sure _HTTP API_ and _API Quick Discovery_ are enabled, see https://github.com/ebaauw/homebridge-nb/issues/73#issuecomment-1174775984.

**Comment by jorgegp93** [comment]
It is solved now, thank you very much for your help.
Congratulations on your job once again.

**Comment by xssociety** [comment]
Ich habe auch zwei Nuki Bridges. Die erste ist eingebunden, wie binde ich nun die zweite ein?
