### ISSUE TITLE
Nuki_Bridge: error: too many callbacks registered after update to 0.0.8

### ISSUE THREAD

**Issue by MikeDeltaHH** [ebaauw/homebridge-nb#8]
Hi!

After updating from 0.0.7 to 0.0.8 the message

Nuki_Bridge: error: too many callbacks registered

appears every minute in the homebridge log!

With 0.0.7 all was fine!

Regrds!
Mike

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-nb/issues/5.

**Comment by MikeDeltaHH** [comment]
Sorry... overlooked... works!!
