### ISSUE TITLE
 Nuki_Bridge_6D37CD90: error: too many callbacks registered

### ISSUE THREAD

**Issue by Scirocco3** [ebaauw/homebridge-nb#81]
Hello,

i've this message every minute in the log.
what's going wrong, there is nothing to configure for the amount of callbacks.
can you help?
thx

**Comment by ebaauw** [comment]
The Nuki bridge only supports three callbacks.

**Comment by Scirocco3** [comment]
Yes, that may be... 
But I only have this Nuki software installed. So the error should come from it. 
That's why I asked if there is a parameter or another solution to this. 
I don't know what else to do except ignore the error or delete the software. 
I don't really plan to do the latter, since I find it useful.

**Comment by ebaauw** [comment]
The error indicates that Homebridge NB cannot register with the Nuki bridge to receive push notifications, because the bridge has already registered three clients.  Consequently, Homebridge NB will only update the status in HomeKit when it next polls the Nuki bridge, causing updates to linger behind.

When you shutdown Homebridge cleanly, Homebridge NB unregisters its callback.  When Homebridge crashes or is killed, a stale callback registration might linger.  Use `nb callbackList` to see the registered callbacks, and `nb callbackRemove` to delete a stale registration manually.  I think they’re also deleted when power cycling the Nuki bridge.

**Comment by Scirocco3** [comment]
Thanks for the help so far...

I turned off the Nuki Bridge and rebooted the Homebridge (so it should shut down cleanly). 
Both unfortunately without success, and the commands do not go "NB" is unknown. It is a Docker Homebridge maybe the command is called differently there?

**Comment by Scirocco3** [comment]
i must write the L in upper case... then then command is recognised.
but i can't find the proper host name...

usage: nb [-hVD] [-H hostname[:port]] [-T token] [-t timeout] command [argument ...]
root@homebridge-prod:/var/lib/homebridge $ nb callbackList
nb: fatal: Missing host.  Set NB_HOST or specify -H.
root@homebridge-prod:/var/lib/homebridge $ nb callbackList -H
nb: fatal: Missing host.  Set NB_HOST or specify -H.
root@homebridge-prod:/var/lib/homebridge $ nb callbackList -H homebridge-prod
nb: fatal: Missing host.  Set NB_HOST or specify -H.
root@homebridge-prod:/var/lib/homebridge $ nb callbackList -H homebridge     
nb: fatal: Missing host.  Set NB_HOST or specify -H.
root@homebridge-prod:/var/lib/homebridge $ nb callbackList -H 192.168.1.94
nb: fatal: Missing host.  Set NB_HOST or specify -H.
root@homebridge-prod:/var/lib/homebridge $

**Comment by ebaauw** [comment]
You need to specify the Nuki bridge, not the container running Homebridge.  And the `-H` comes before the command.

**Comment by Scirocco3** [comment]
Now he want's a token... But what exactly ?

root@homebridge-prod:/var/lib/homebridge $ nb -H nuki callbackList
nb: fatal: Missing token.  Set NB_TOKEN or specify -T.  Run nb -H nuki auth to obtain the token.

root@homebridge-prod:/var/lib/homebridge $ nb -H nuki auth        
nb auth: press button on Nuki bridge to obtain token
nb auth: nuki: request 1: GET /auth
nb auth: warning: nuki: request 1: error: getaddrinfo ENOTFOUND nuki
nb auth: fatal: getaddrinfo ENOTFOUND nuki

root@homebridge-prod:/var/lib/homebridge $

**Comment by ebaauw** [comment]
ENOTFOUND means `nb` cannot resolve `nuki`.  See the Homebridge log or run `nb discover` to find the IP address of the Nuki bridge.

**Comment by Scirocco3** [comment]
Thank you, error fixed.

First I had to get another token, then I could query the callbacks and all 3 were old IP address. I deleted all 3 and now it works. Only the callback from HB is still there. Thanks a lot
