### ISSUE TITLE
Nuki Door sensor - no last known state

### ISSUE THREAD

**Issue by MirkoKas** [ebaauw/homebridge-nb#84]
I just replaced my Nuki 2 with a Nuki 3 and added one of these new door sensors. 
Everything added to HomeKit through the plugin easily.

I recently noticed that the door sensor started to not work anymore within HomeKit.  
In the homebridge log I get the message/warning no known last state every heartbeat (20seconds in my case). I already checked with the Nuki app and the status updates here like it should and shows door open / closed but in HomeKit it’s always closed. 

I run the newest version of homebridge and this plugin.

**Comment by MirkoKas** [comment]
Here’s a screen of the log 

![Uploading 8C547151-88A6-476D-ABD8-D5A9BF449E31.jpeg…]()

**Comment by ebaauw** [comment]
Looks like the connection between the smart lock and Nuki bridge has been lost.  The Nuki app connects to the smart lock directly over BLE., so it isn’t affected.

Normally the Nuki bridge caches the smart lock state.  Homebridge NB polls the bridge for this cached state, to preserve the smart lock battery.  The message means the Nuki bridge doesn’t report a last known state for the smart lock.   You might try and _Identify_ the smart lock from HomeKit, so Homebridge NB asks the bridge to connect to the smart lock over BLE, updating the lock state.

If that fails, check the smart lock _Connection status_ in the Nuki app: you should see a direct connection between your phone and the lock, as well as a connection over the Nuki bridge and server.  If the latter is missing, try and power cycle the Nuki bridge.  If that doesn’t solve the issue, you might have to re-pair the smart lock with the Nuki bridge, making sure they are within BLE range of each other.

**Comment by MirkoKas** [comment]
As Inwas away from home when I saw your reply I checked the status within the Nuki App and there was a green connection between the lock and the bridge to the server. So I assume the connection between those two are fine. 
i also did an identity in HomeKit but that didn’t change anything. 
any other suggestion what could be going on here?

**Comment by MirkoKas** [comment]
One more thing: I noticed that Eve is showing the status correctly and is counting also correctly how often the door was opened/closed. The homebridge log still shows that it doesn’t have the correct state while it definitely is there. 

Some screens:
![FA424850-0CA6-4AC8-A781-90FB9CE319C1](https://user-images.githubusercontent.com/36824593/187025627-1d03a7e7-c034-463f-b130-be4874938d83.png)
![C2F5C207-2C5F-47FF-BD66-1181B9AA8283](https://user-images.githubusercontent.com/36824593/187025629-cbdf6b29-4ec5-4d0c-9a3f-231e5a5760de.png)
![DD90DA49-7D56-4B98-924B-88987781EDD7](https://user-images.githubusercontent.com/36824593/187025632-dd60dfe1-239e-4116-8e9c-a68caf3e8b2a.png)

**Comment by ebaauw** [comment]
Could you please list the output of `nb info` and of `nb list`?  Maybe it's a stale entry for the old smart lock?

**Comment by MirkoKas** [comment]
I think you are right. The sensor that is reporting no state is the old one that is currently offline. I renamed the lock within the Nuki App but it seems that the nb plugin still has the old names. Is there a way to trigger an update of the names?

When I replaced the Nuki I first gave the new one a different name and after final replacing steps I renamed the new one to have the name of the old one and gave the older one a completely new name. In the Nuki App everything looks good. 

![CC69B4D5-E4E3-4B74-AF33-8AD562E152C0](https://user-images.githubusercontent.com/36824593/187044930-b25218ef-8003-48d8-8aae-1c1f2c7fee65.jpeg)
![E625CB6B-7C87-4EB2-91C7-84EF8845A5F5](https://user-images.githubusercontent.com/36824593/187044931-1523b660-386f-462a-95c0-1d5188eb629d.jpeg)

**Comment by ebaauw** [comment]
> I renamed this lock within the Nuki App but it seems that the nb plugin still has the old names.

That’s because the Nuki bridge that still reports the old name, as you can see above.

> Is there a way to trigger an update of the names?

No, once an accessory or service has been exposed, their names are managed in HomeKit, and cannot be changed by the accessory itself (i.c. the Homebridge plugin).  Changing the name on the Nuki bridge would change the name used by Homebridge NB in the log, though.

**Comment by MirkoKas** [comment]
> Changing the name on the Nuki bridge would change the name used by Homebridge NB in the log, though.

that did the trick. Somehow the bridge didn’t got the new name for one of the locks. The other one was already ok. After renaming that lock again and checking again in the configure of the bridge, all the names were correct.
After restarting nb plugin the message is also now gone. So something just got mixed up! Thx for your help.
