### ISSUE TITLE
Doorbell Accessories not visible in the Home.app

### ISSUE THREAD

**Issue by patricks** [ebaauw/homebridge-nb#85]
I have enabled this plugin on my Homebridge and I can see 3 accessories (locks). I have also an Opener but shouldn't there be also a doorbell accessory? Is there a way do enable / disable it? I didn't find any config for that.

**Comment by ebaauw** [comment]
Homebridge NB exposes the Opener as a single accessory, with services for _Lock Mechanism_, _Doorbell_, and _Battery_.  The _Doorbell_ service doesn't show in Home, see also #79.  You'll have to ask Apple for the reason why.
