### ISSUE TITLE
Feature Request: No Auto-Lock for Opener

### ISSUE THREAD

**Issue by mmz06** [ebaauw/homebridge-nb#86]
I'm using your very nicely working plugin for some time now with my Nuki Opener.
It is to control my garden gate actually, so each push open or closes the portal which is oaky but could be augmented if I could add my Eufy door sensor to the mix.
But then I would need an option in your plugin not to auto lock, so I could set this lock via an HomeKit automation.
In the mean, time thank you very much for this plugin, it works so well  !!!

**Comment by ebaauw** [comment]
I’m sorry, I don’t understand your request.  The Nuki Opener only supports an _Open_ action (see the Nuki app), not _Unlock_ and _Lock_.  It’s exposed to HomeKit as a _Lock Mechanisn_, because I couldn’t find anything better.  Setting _Unlocked_ translates to _Open_, but setting _Locked_ does nothing.  The HomeKit state reverts to _Locked_ automatically, so you can set _Unlocked_ again, but that doesn’t lock the opener.

**Comment by mmz06** [comment]
Okay I totally agree with you. What I'm looking at is an option from your plugin which will allow not to revert automatically the HomeKit state as Locked, so I can trigger this locked state by using another HomeKit accessory which is essentially a door sensor (https://us.eufy.com/products/t8900).
The idea is to bring more smart to the Nuki Opener, by using HomeKit, your plugin and this sensor, so this garden gate can be used remotely.

**Comment by ebaauw** [comment]
Commit https://github.com/ebaauw/homebridge-nb/commit/1d8cb775d627daf6d377c958991882a399bf39e6 should have linked here.

**Comment by ebaauw** [comment]
Could you try beta v1.2.11-0?

This version adds a `openerResetTimeout` config.json setting to configure the timeout before an Opener reverts to locked.  Set this to 0 to prevent an Opener from reverting altogether.  
Note that this setting affects all Openers; I won't be providing a setting per Opener from config.json, as that would mean users finding out the ID of the Opener and copy/pasting that into config.json.

**Comment by mmz06** [comment]
This option looks exactly to what I'm looking for.
I will give it a try as soon as I'm back home during the weekend hopefully.
I'll update this thread with the results.
Thank you for your fast feedback !

**Comment by mmz06** [comment]
Unfortunately, it seems to fail. I configured the `openerResetTimeout` to `0`, but it still unlocks then goes back to lock state.
Here are HomeBridge logs (set at level 3), after a single press on the HomeKit unlock button:

`[9/24/2022, 3:24:56 PM] [Nuki] Nuki_Bridge_7F2C7287: set Last Updated from "Sat Sep 24 2022 15:24:46" to "Sat Sep 24 2022 15:24:56"`
`[9/24/2022, 3:25:02 PM] [Nuki] Portail: Lock Target State changed from 1 to 0`
`[9/24/2022, 3:25:07 PM] [Nuki] Portail: set Lock Current State from 1 to 0`
`[9/24/2022, 3:25:08 PM] [Nuki] Nuki_Bridge_7F2C7287: set Last Updated from "Sat Sep 24 2022 15:24:56" to "Sat Sep 24 2022 15:25:08"`
`[9/24/2022, 3:25:08 PM] [Nuki] Portail: set Lock Current State from 0 to 1`
`[9/24/2022, 3:25:08 PM] [Nuki] Portail: set Lock Target State from 0 to 1`
`[9/24/2022, 3:25:08 PM] [Nuki] Portail: set Last Updated from "Sat Sep 24 2022 14:59:24" to "Sat Sep 24 2022 15:25:08"
`

**Comment by ebaauw** [comment]
> Here are HomeBridge logs (set at level 3)

There are no debug messages in the log.  Did you run Homebridge in DEBUG mode?  Did you set _Log Level_ on the Nuki Bridge accessory?

Regardless, I think I understand what's happening:

> [9/24/2022, 3:25:02 PM] [Nuki] Portail: Lock Target State changed from 1 to 0

You set the Opener to Unlocked from HomeKit.  The `openerResetTimeout` of 0 does actually work, as the state isn't reset within 500ms.

> [9/24/2022, 3:25:07 PM] [Nuki] Portail: set Lock Current State from 1 to 0

Not sure where this comes from, but I suspect the bridge sends a notification when the Opener state changes from opening (7) to open (5).

> [9/24/2022, 3:25:08 PM] [Nuki] Nuki_Bridge_7F2C7287: set Last Updated from "Sat Sep 24 2022 15:24:56" to "Sat Sep 24 2022 15:25:08"
[9/24/2022, 3:25:08 PM] [Nuki] Portail: set Lock Current State from 0 to 1
[9/24/2022, 3:25:08 PM] [Nuki] Portail: set Lock Target State from 0 to 1
[9/24/2022, 3:25:08 PM] [Nuki] Portail: set Last Updated from "Sat Sep 24 2022 

When Homebridge NB next polls the bridge, it reports the Opener state as online (1), and Homebridge NB updates the HomeKit state accordingly.

As I mentioned earlier, the opener is more like a push button, unlike the smart lock which is like a stateful switch.  What you want is a stateful lock, where the state is based on the sensor, and state change is handled by the Opener.  This level of automation logic is beyond the scope of Homebridge NB.  As a Homebridge plugin, it simply synchronises the state of the Opener with HomeKit.

**Comment by mmz06** [comment]
I see your point, and I understand that Homebridge NB really syncs Opener status with HomeKit.
And you are totally right on what you say in terms if statefulness I'd like to add to it.
What I can't imagine is that this change is impossible from the side of your plugin.
The idea really is if the HomeKit button status is unlocked, then don't change it, even if Opener reports a different status.
I may be blind, forgetting something important, as a total non expert here, but well if you can make it happen...

**Comment by ebaauw** [comment]
> What I can't imagine is that this change is impossible from the side of your plugin.

It would be technically feasible to make the change.  I won't be doing so, because it's functionally undesirable to let the scope creep from exposing Nuki devices to implementing home automation logic.

It's open source - you're more than welcome to copy my code, and make your own plugin with the logic you want.

**Comment by mmz06** [comment]
Alright, thank you for your time and explanations anyway. This was much appreciated
