### ISSUE TITLE
Delay to state lock as "locked"

### ISSUE THREAD

**Issue by cpvbruno** [ebaauw/homebridge-nb#87]
I have my Nuki Smart Lock 3.0 in Homekit via Bluetooth (official way) and via this plugin. Bluetooth reports the states (locked/unlocked) very fast, but this plugin takes long to report "locked", "unlocked" is fine.

Anything that can be improved?

**Comment by ebaauw** [comment]
Check the Homebridge log and make sure Homebridge NB subscribes to the notifications by the Nuki bridge.  Using `nb callbackList`, check that Homebridge NB is the only, or at least the first callback.  Check the Bluetooth connection between the Smart Lock and the Bridge, using `nb list`.

**Comment by ebaauw** [comment]
Oops, above commit is for #86.
