### ISSUE TITLE
How to set NB_TOKEN and NB_HOST variable?

### ISSUE THREAD

**Issue by MirkoKas** [ebaauw/homebridge-nb#89]
Hi, 
I don’t find any documentation where and how to set NB_TOKEN and NB_HOST variables to not have to enter them manually each time I use the command line. 

Thx for your help.

**Comment by ebaauw** [comment]
These are environment variables.  On Linux/Unix you’d want to set them from your `.profile` or similar, using `export`.  It’s been well over a decade since I used Windows, and I’m afraid I no longer remember how to set them on there.

**Comment by MirkoKas** [comment]
Thx. That was enough context for me to use google and find some instructions how to do this. Never set any environment variables before, so I had no clue what to at first :-D

works like a charm now
