### ISSUE TITLE
Every homebridge reboot generate a new callback id

### ISSUE THREAD

**Issue by MikeDeltaHH** [ebaauw/homebridge-nb#9]
II´ve deleted all callbacks ids last week but homebridge now reported again too many callbacks in the logs - i made some tests - every homebridge reboot generates a new callback id because nb use different ports, as example:

homebridge@homebridge-server:~$ nb -H 192.168.2.55:8080 -T xxx callbackList
{
  "callbacks": [
    {
      "id": 0,
      "url": "http://192.168.2.251:38431/notify/5DDE33F4"
    },
    {
      "id": 1,
      "url": "http://192.168.2.251:40095/notify/5DDE33F4"
    },
    {
      "id": 2,
      "url": "http://192.168.2.251:37069/notify/5DDE33F4"
    }

**Comment by ebaauw** [comment]
How do you reboot Homebridge?  Homebridge NB removes the callback on controlled shutdown, so they shouldn’t linger.

**Comment by MikeDeltaHH** [comment]
Reboot every night the complete ubuntu server as a planned task but a manual reboot with config-ui-x (after a plugin update as an example) has the same affect!

**Comment by ebaauw** [comment]
How do you stop homebridge?

**Comment by MikeDeltaHH** [comment]
In config-ui-x i do a restart over the restart button:

![Reboot HB](https://user-images.githubusercontent.com/34737987/101344105-425b0800-3885-11eb-8d51-cff57da951e5.jpg)

Daily eboot over a planned cron job:

![daily reboot](https://user-images.githubusercontent.com/34737987/101344142-5272e780-3885-11eb-8117-670442f1701b.jpg)

**Comment by ebaauw** [comment]
Could you please enable debug mode, restart Homebridge and attach the logfile?

**Comment by MikeDeltaHH** [comment]
I change the cron job command to shutdown -r now and execute the job, but with no success - the callback ids are not deleted

Enable debug mode, reboot and  attach a log:

[homebridge.log.txt](https://github.com/ebaauw/homebridge-nb/files/5652412/homebridge.log.txt)

**Comment by ebaauw** [comment]
Looks like the HomeMatic plugin installs its own SIGTERM signal handler, replacing the Homebridge signal handler.  It should do its cleanup on the Homebridge `shutdown` event instead.  Because of this, the `shutdown` event isn't issued, so none of the other plugins can do a proper shutdown.  It might even cause issues with the `cachedAccessories` not being flushed.
```
[12/7/2020, 12:37:08 PM] [Homebridge UI] Homebridge restart request received
[12/7/2020, 12:37:09 PM] [Homebridge UI] No restart command defined, killing process...
[12/7/2020, 12:37:09 PM] [HB Supervisor] Stopping services...
[12/7/2020, 12:37:09 PM] Got SIGTERM, shutting down Homebridge...
[12/7/2020, 12:37:09 PM] [Harmony] INFO - shutdown
[12/7/2020, 12:37:09 PM] [Apple TV Platform] Shutting down Apple TV clients...
[12/7/2020, 12:37:09 PM] [HomeMatic CCU3] [RPC] Removing Event Server for Interface BidCos-RF.
[12/7/2020, 12:37:09 PM] [HomeMatic CCU3] [RPC] Removing Event Server for Interface BidCos-Wired.
[12/7/2020, 12:37:09 PM] [HomeMatic CCU3] [RPC] Removing Event Server for Interface HmIP-RF.
[12/7/2020, 12:37:09 PM] [Sonos] goodbye
[12/7/2020, 12:37:09 PM] [Hue] goodbye
[12/7/2020, 12:37:09 PM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null
```

**Comment by MikeDeltaHH** [comment]
Oh... ok... not so good... so i have to do a manual remove of the callbacks, need the HomeMatic Plugin! Thanks for your support and the very good plugin!

**Comment by ebaauw** [comment]
You could file an issue with the HomeMatic plugin.  And in the meantime run HomeMatic in a separate Homebridge instance.

The "callbacks" (subscriptions) for Sonos are also not cleaned up, but they support more than 3 and expire automatically, so you're less likely to notice.

**Comment by MikeDeltaHH** [comment]
Ok, thanks for information, will do that! 👍
