### ISSUE TITLE
Meaning of the Switch (Eve App)

### ISSUE THREAD

**Issue by Pi88no** [ebaauw/homebridge-nb#91]
Yesterday I integrated my Nuki Opener incl. Nuki Bridge with Homebridge + NB Plugin.

According to the instructions, you can use some additional Festures via the Eve app.

What is a mystery to me here, what exactly is supposed to become Enable here?

I could not see any change in the opener. 

![2D9020C1-A90D-4DD3-824C-10CDFCB61776](https://user-images.githubusercontent.com/100616809/202686220-8bb46471-de6a-4782-886e-8455dc798256.jpeg)

**Comment by ebaauw** [comment]
Whether Homebridge NB should issue a HomeKit even when the doorbell is pressed.  Some folks didn’t like their HomePods going off in the middle of the night, but Apple doesn’t provide a setting for that.  As a workaround, you can use this setting to disable (or rather prevent) all HomeKit notifications for the doorbell.

**Comment by Pi88no** [comment]
Ok, that explains that my opener does not visibly change any settings. Thanks!

For better understanding for me, this additional question. I have named the devices displayed in the Eve app as I understand them, is that correct?

- Nuki Bridge
- Opener
- Homebridge (on raspberry)
- NukiBridge Plugin (on raspberry)

is that correct that the plugin is displayed as a device?

**Comment by ebaauw** [comment]
No, Homebridge NB only provides accessories for the Nuki bridge and connected Openers and Smart Locks.  I think you’re running Homebridge NB in a child bridge, which would show as a separate bridge accessory in HomeKit.

**Comment by Pi88no** [comment]
Can I run Homebridge-NB as a non child bridge? I have installed Homebridge-NB through Homebridge Config UI as described in the tutorial.

**Comment by ebaauw** [comment]
Not recommended, but yes, you can.

**Comment by Pi88no** [comment]
Okay. Thank you. 

One more question: the log level can be set from 0-3? Is there a documentary to find out what which level means?

**Comment by ebaauw** [comment]
There is: https://github.com/ebaauw/homebridge-lib/wiki/Log-Messages
