### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Almansio** [ebaauw/homebridge-nb#97]
Hey Eric,

First of all I would like to thank you for your effort. 

Is there a step for step installation guide, I can't figure out how to config/connect my nuki in homebridge. 

I have a nuki 3.0 pro without a bridge and run homebridge on a RaspberryPi.

Much appreciated!

**Comment by ebaauw** [comment]
Please read the first sentence in the README.

**Comment by Almansio** [comment]
My bad, I thought the pro had a build in bridge and therefore compatible. Thanks for the swift reply. Op 19 feb. 2023 om 00:59 heeft Erik Baauw ***@***.***> het volgende geschreven:﻿
Please read the first sentence in the README.

**Comment by ebaauw** [comment]
I does WiFi, but it doesn’t support the HTTP API by the Nuki bridge, and this is what Homebridge NB uses.
