### ISSUE TITLE
http stat us 503 Service Unavailable

### ISSUE THREAD

**Issue by Ju17091** [ebaauw/homebridge-nb#98]
Hello,
Can anyone help me ? Can anyone tell me what this message means? 
Comes again and again. Plugin works great. I just get this error message in my Homebridge protocol every now and then.
Thanks in advance

![6883A716-2128-443C-9D06-9078C494DC89](https://user-images.githubusercontent.com/119397275/221438097-b602c040-85e9-4753-bb6f-52122618afd0.jpeg)

**Comment by ebaauw** [comment]
Search the closed issues.
